### ISSUE TITLE
cec doesn't work with no tv attached

### ISSUE THREAD

**Issue by djbijo** [Pulse-Eight/libcec#104]
i have a cec enabled avr (onkyo 535) connected to cubox-i with kodi (openelec).
my tv doesn't support cec.
chromecast work's fine (switching input when somthing is playing).
i can see the key presses in kodi's log but they are ignored and i also can't control the avr's volume.
 i also see the error:

[code]
CecLogMessage - << Recorder 1 (1) -> TV (0): POLL
00:42:52 T:1487889472   DEBUG: CecLogMessage - << 10
00:42:52 T:1487889472   ERROR: CecLogMessage - Write: sent command error !
00:42:52 T:1487889472   DEBUG: CecLogMessage - << 10
00:42:52 T:1487889472   ERROR: CecLogMessage - Write: sent command error !
00:42:52 T:1487889472   DEBUG: CecLogMessage - >> POLL not sent
[/code]

all the time

can you add support (maybe add setting?) for the case that no tv is available? 
also, when using Xbian it works fine somehow, maybe they changed the code?

**Comment by opdenkamp** [comment]
the CEC spec says that the TV should support CEC too, and the code will keep trying to poll the TV for that reason.

I've changed the code to not treat a failed ack from the TV as error when sending an active source message, which will be included in tomorrow's 3.0.1 update.

no idea what xbian is using or if they've changed anything.

**Comment by djbijo** [comment]
i realize that this is the spec but there is no reason why it shouldn't work without cec enabled tv.
you have the power to overcome the spec's bugs and at least add the option to disable tv polling so this will still work with only CEC enabled AVR.
