### ISSUE TITLE
RFC: Support Fire TV Stick

### ISSUE THREAD

**Issue by kfix** [Pulse-Eight/libcec#105]
The Amazon Fire TV Stick (not the "box") is a Broadcom VideoCore based device running an Android 4.2 derivative.
Its fairly locked down, but does allow remote ADB to be enabled which enables an unprivileged shell as well as sideloading APKs like Kodi media player.

`/dev/vchiq` is present and a program named `cecdaemon` uses it to pass incoming CEC commands to Android via evdev (`/sys/class/input/input1/name`).

I'd like to "port" libcec/adapters/RPi so Kodi can use cec-client to switch the TV's A/V input to the stick, switch it back to tuner when done, etc. Is it just a matter of enhancing the detection logic to look for Fire TV's traits instead of RPi's?

**Comment by opdenkamp** [comment]
yeah sounds like the Pi's implementation should work here too, though you'll have to remove than daemon and give exclusive access to libCEC
