### ISSUE TITLE
Eventghost plugin submit raw command fails

### ISSUE THREAD

**Issue by etheralm** [Pulse-Eight/libcec#107]
I am trying to migrate my setup to the new libcec plugin for eventghost, but I ran into an issue with the submit command action. 

The plugin initializes properly and I am able to turn the tv on and off, but when I submit the command "tx 1f 82 20 00"  nothing happens. If I use cec-client.x64.exe to submit the command the tv switches to hdmi 2 as expected. 

Following is the log from eventghost: http://pastebin.com/ejL4tBS2
And the log from cec-client.x64.exe: http://pastebin.com/1SBF72Dw

Thanks in advance for the help. Let me know if I can help with anything else.

**Comment by opdenkamp** [comment]
you're using the raw command's parameters incorrectly. the command to be sent should be "1f:82:20:00". I've just tested this while building the latest version (in a local branch) from source, which will be used for tomorrow's 3.0.1 update.
