### ISSUE TITLE
DESTDIR mess with cmake

### ISSUE THREAD

**Issue by Gottox** [Pulse-Eight/libcec#118]
With libcec-3.0 cmake fails to install files to the right directory. Our [post_install script](https://github.com/Gottox/void-packages/blob/890772ecbef9b82560364ee96b2dee5cc1501e52/srcpkgs/libcec/template#L29) cleans it up, but it would be great if this would be fixed in libcec directly. Same issue happened with [libplatform](https://github.com/Gottox/void-packages/blob/d48b47a9ea5ce7b6434bc470fbe7deb7f116b5a2/srcpkgs/platform/template#L15)

**Comment by opdenkamp** [comment]
should be fixed after https://github.com/Pulse-Eight/libcec/pull/119
