### ISSUE TITLE
Tuner Status

### ISSUE THREAD

**Issue by EMJB** [Pulse-Eight/libcec#121]
I would like to be able to monitor the channel selection of my TV. Is this possible with CEC, and if so is it supported by libcec? - I have not found any relevant reference but perhaps I am searching for the wrong terms.

**Comment by malard** [comment]
Sadly not, it is impossible with CEC, maybe with the RS232 you can on some models

**Comment by EMJB** [comment]
Many thanks for that information, and for replying so quickly.

EMJB
