### ISSUE TITLE
Reference to Issue #84

### ISSUE THREAD

**Issue by guywilsonjr** [Pulse-Eight/libcec#122]
The last commenter wrote a post about an error he was getting from following those instructions. I receive the same error when I follow those instructions, yet it also says Raspberry pi support yes. I tried following your last comment and just using the instructions from Readme.md and when I do the cmake call I get Raspberry pi support: no. Due to these reasons I feel like those instructions may still be valuable and it would be nice if you left the install commands in the readme as it isn't evident the command you need to make to get those libraries and headers. I would consider reopening Issue 84 if possible or if anyone else has been able to overcome this do you have any potential solutions? The results below come from a fresh installation of rapbian and the following apt-get commands
```sudo apt-get install cmake g++-4.8```
```sudo apt-get install liblockdev1-dev libudev-dev libxrandr-dev```
```sudo apt-get install python-dev swig```
```git clone --recursive git://github.com/Pulse-Eight/libcec.git```

-Modify ~/libcec/src/libcec/cmake/CheckPlatformSupport.cmake(notice I don't modify the check_library_exists function as the latest file is different than the original posters)
and below 'set(LIB_INFO "${LIB_INFO}, 'RPi'")' add
```include_directories(/opt/vc/include /opt/vc/include/interface/vcos/pthreads /opt/vc/include/interface/vmcs_host/linux)```
-Build platform package.

```cd ~/libcec/src/platform```
```mkdir build```
```cd build```
```cmake -DCMAKE_CXX_COMPILER=g++-4.8 ..```
```make```
```sudo make install```

-Build libcec library

```cd ~/libcec```
```mkdir build```
```cd build```
```export LIBRARY_PATH=/opt/vc/lib```
```cmake -DCMAKE_CXX_COMPILER=g++-4.8 -DCMAKE_INSTALL_PREFIX=/usr -``````DBUILD_SHARED_LIBS=1 ..```
```make```
```sudo -E bash -c 'make install'```

Using the instructions posted in the issue I get
-- Found SWIG: /usr/bin/swig2.0 (found version "2.0.12")
-- Configured features:
-- Pulse-Eight CEC Adapter:                yes
-- Pulse-Eight CEC Adapter detection:      yes
-- lockdev support:                        yes
-- xrandr support:                         yes
-- Raspberry Pi support:                   yes
-- TDA995x support:                        no
-- Exynos support:                         no
The errors are:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
RPI_BCM_HOST
linked by target "cec" in directory /root/distr/libcec/src/libcec
RPI_VCHIQ_ARM
linked by target "cec" in directory /root/distr/libcec/src/libcec
RPI_VCOS
linked by target "cec" in directory /root/distr/libcec/src/libcec

-----------------------------------------------------------------------------------------
Using the instructions from the readme file i get
-- Found SWIG: /usr/bin/swig2.0 (found version "2.0.12")
-- Configured features:
-- Pulse-Eight CEC Adapter:                yes
-- Pulse-Eight CEC Adapter detection:      yes
-- lockdev support:                        yes
-- xrandr support:                         yes
-- Raspberry Pi support:                   no
-- TDA995x support:                        no
-- Exynos support:                         no
-- Python support:                         version 2.7.9 (2.7)
-- lib info: compiled on Linux-3.18.11+, features: P8_USB, P8_detect, randr
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/libcec/build

**Comment by opdenkamp** [comment]
Sorry, but this is wrong. If you follow the instructions in the readme file to the letter on a virgin installation of Raspbian, then everything builds just fine. Do _not_ edit any files.

The only difference between a standard Debian/Ubuntu installation and one for Raspberry Pi is the path to the Pi's headers and libs that you need to specify and that's only needed if it's not already in the system's search paths.

```
apt-get update
apt-get install cmake liblockdev1-dev libudev-dev libxrandr-dev python-dev swig
cd
git clone https://github.com/Pulse-Eight/platform.git
mkdir platform/build
cd platform/build
cmake ..
make
sudo make install
cd
git clone https://github.com/Pulse-Eight/libcec.git
mkdir libcec/build
cd libcec/build
cmake -DRPI_INCLUDE_DIR=/opt/vc/include -DRPI_LIB_DIR=/opt/vc/lib ..
make
sudo make install
sudo ldconfig
```

```
pi@raspberrypi:~/libcec/build $ cec-client -i
libCEC version: 3.0.1, git revision: <unknown>, compiled on Wed Nov 25 15:56:10 UTC 2015 by pi@raspberrypi on Linux 4.1.13-v7+ (armv7l), features: P8_USB, P8_detect, randr, 'RPi'
```
