### ISSUE TITLE
Guide for raspberry compilation

### ISSUE THREAD

**Issue by teopost** [Pulse-Eight/libcec#127]
Please,
   add a quick guide for raspberry pi compilation !

**Comment by mrgreywater** [comment]
```
sudo apt-get install cmake g++-4.8 liblockdev1-dev libudev-dev libxrandr-dev python-dev swig
git clone --recursive git://github.com/Pulse-Eight/libcec.git
cd ~/libcec/src/platform
mkdir build
cd build
cmake -DCMAKE_CXX_COMPILER=g++-4.8 ..
make
sudo make install
cd ~/libcec
mkdir build
cd build
export LIBRARY_PATH=/opt/vc/lib
cmake -DCMAKE_CXX_COMPILER=g++-4.8 -DRPI_INCLUDE_DIR=/opt/vc/include -DRPI_LIB_DIR=/opt/vc/lib -DBUILD_SHARED_LIBS=1 -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=1 ..
make -j4
sudo -E bash -c 'make install -j4'


```

**Comment by conect** [comment]
Would be nice if somone could include this into the readme.

**Comment by Aupajo** [comment]
I've added this as a wiki page for the mean-time: https://github.com/Pulse-Eight/libcec/wiki/Raspberry-Pi-set-up

**Comment by opdenkamp** [comment]
I've updated the README.md file with more detailed instructions: https://github.com/Pulse-Eight/libcec/commit/2e880768f33b6b40b518ecc23fe9da1bb6d43bc3
Also updated the wiki page with these instructions
