### ISSUE TITLE
TV remote actions executed twice

### ISSUE THREAD

**Issue by Forage** [Pulse-Eight/libcec#13]
Ever since OpenElec 4 beta 1 (including beta 2), the actions of my TV remote are often applied twice. It happens throughout the UI. E.g. in lists where pressing "down" once results in going down two steps, or when pressing a button, etc.

Here's a log where it happened again: http://xbmclogs.com/show.php?id=150377
Note that there's a major snip at line 255, due to a different test I performed first.

In this case I navigated to the shutdown button, pressed it, and it went strait through to powering down because that would have been the next selected option, even though I only pressed the button once. This is where the log, obviously, stops.

System: Raspberry Pi
OS: OpenElec 4.0 beta 2
TV+remote: Panasonic VIERA G30

Let me know if you need any more information.

**Comment by josh4trunks** [comment]
@opdenkamp what are we still missing for this issue to be squashed? OpenELEC 5.0 + CEC Adapter (v4 firmware) + Panasonic Viera + KEYSPAN ER-V2 RF Remote I am still experiencing this.
Thanks

**Comment by Forage** [comment]
@josh4trunks That sounds like a different issue if you as me. Your remote is an RF remote, not using (lib)CEC at all. Were this issue applied to remotes that controlled OpenElec through controlling your TV, you are controlling OpenElec directly.

**Comment by josh4trunks** [comment]
Ahh, didn't realize that. OK, I may need to create a separate issue

**Comment by xraynorm** [comment]
My issue was fixed when I upgraded to helix. Tested libcec 2.1.4 and 2.2.0 both fine on helix
(x86, usb cec, Panasonic TV + av amp).

Thanks to whoever fixed this.
