### ISSUE TITLE
Turn TV on and off as Windows screen goes on and off

### ISSUE THREAD

**Issue by Slion** [Pulse-Eight/libcec#135]
I was looking for an option to turn on and off the TV as Windows turn its screen on and off just with libCECTray and without XBMC.

**Comment by opdenkamp** [comment]
This is not implemented at this time

**Comment by Slion** [comment]
See:https://github.com/Pulse-Eight/libcec/issues/138

**Comment by Slion** [comment]
So I publish a new version of my Sharp Display Manager software supporting CEC.
Thanks to you guys.
See:
http://forum.team-mediaportal.com/threads/minidisplay-for-sharp-display-manager.127180/page-2#post-1153974

It would be nice if MediaPortal could support Remote Control Pass Through. It could be a while until I get to work on that though.
