### ISSUE TITLE
CECTray.cs can't be opened in designer

### ISSUE THREAD

**Issue by Slion** [Pulse-Eight/libcec#139]
VS 2013 Community can't open CECTray.cs and a couple of other forms in designer.
Is that a known issue?

**Comment by opdenkamp** [comment]
Yeah, this is because the designer isn't smart enough to handle `https://github.com/Pulse-Eight/libcec/blob/master/src/LibCecTray/ui/AsyncForm.cs` as base class. As a work around, change the base to `Form` while in designer and change it back when you're done.
