### ISSUE TITLE
cec.dll vs libcec.dll

### ISSUE THREAD

**Issue by Slion** [Pulse-Eight/libcec#140]
Building the sources on master generates a file name cec.dll.
Why is it called libcec.dll when installed from the 2.2.0 Windows installer?
I'm trying to put together a NuGet package.
Does the release branch still contain the sources for 2.2.0?

**Comment by opdenkamp** [comment]
the binary got renamed in 3.0. all releases, including sources, can be found here: https://github.com/Pulse-Eight/libcec/releases
