### ISSUE TITLE
CEC connection usage

### ISSUE THREAD

**Issue by Slion** [Pulse-Eight/libcec#145]
Can libcec somehow get disconnected? Do I need to implement a reconnect mechanism in my applications? 

When using Remote Control Passthrough I guess the connection needs to be always on. For now I'm only using Power On and Standby feature from my TV. Therefore I could only open the connection whenever needed rather than maintaining it. Would there be any benefit in doing that? Would it be more stable?

I'm just considering the options I have to try and improve stability of the system following the breakdown I had: https://github.com/Pulse-Eight/libcec/issues/144

**Comment by opdenkamp** [comment]
Yes, the connection to the device can get lost, e.g. when the system goes to standby or when the device is unplugged.

You'll receive a `libcec_alert` of type `CEC_ALERT_CONNECTION_LOST`. See https://github.com/Pulse-Eight/libcec/blob/release/src/cec-client/cec-client.cpp#L222 for an example
