### ISSUE TITLE
Segfault on Intel platform when /sys/class/drm/<card>/edid has zero length 

### ISSUE THREAD

**Issue by Cheddoleum** [Pulse-Eight/libcec#147]
Getting a segfault in kodi when initializing libcec, due to an unexpected condition in /sys/class/drm.

`/sys/class/drm/card0-eDP-1/enabled` contains "enabled"
`/sys/class/drm/card0-eDP-1/edid` is empty, contains zero bytes

`libcec/platform/drm/drm-edid.cpp:CDRMEdidParser::GetPhysicalAddress` walks `/sys/class/drm/` and detects `card0-eDP-1/enabled` (contains "enabled");
reads zero bytes from `/edid` (iPtr == 0);
calls `CEDIDParser::GetPhysicalAddressFromEDID(buf,iPtr)`.

In /`src/libcec/platform/util/edid.h`:
`CEDIDParser::GetPhysicalAddressFromEDID(unsigned char *data, size_t size)` contains a runaway for loop:

      for (size_t iPtr = 0; iPtr < size - 4; iPtr++)

 when the second argument is zero (subtracting 4 from zero in an unsigned type yields a very large number) it will inevitably read from an invalid memory location, and segfault.

Tested with the following change: 

    diff --git a/src/libcec/platform/drm/drm-edid.cpp b/src/libcec/platform/drm/drm-edid.cpp
    index 279282b..a69c59a 100644
    --- a/src/libcec/platform/drm/drm-edid.cpp
    +++ b/src/libcec/platform/drm/drm-edid.cpp
    @@ -118,7 +118,11 @@ uint16_t CDRMEdidParser::GetPhysicalAddress(void)
               buf[iPtr++] = c;
           }
        
    -      iPA = CEDIDParser::GetPhysicalAddressFromEDID(buf, iPtr);
    +      if (iPtr)
    +      { 
    +        iPA = CEDIDParser::GetPhysicalAddressFromEDID(buf, iPtr);
    +      }
    +
           fclose(fp);
         }
       }

This corrects the problem.   Arguably edid.h should probably also change to return the default  immediately when the value of the `size` argument would produce an invalid result:

    diff --git a/src/libcec/platform/util/edid.h b/src/libcec/platform/util/edid.h
    index 9a49c44..dbe04de 100644
    --- a/src/libcec/platform/util/edid.h
    +++ b/src/libcec/platform/util/edid.h
    @@ -50,6 +50,11 @@ namespace PLATFORM
         {
           uint16_t iPA(0);
     
    +      if (size < 4) 
    +      {
    +        return iPA;
    +      }
    +
           for (size_t iPtr = 0; iPtr < size - 4; iPtr++)
           {
             if (data[iPtr]     == 0x03 &&

Details:
Kernel 3.19.0-30-generic #34~14.04.1-Ubuntu SMP Fri Oct 2 22:09:39 UTC 2015 x86_64
libcec git master 2c675dac48387c48c7f43c5d2547ef0c4ef5c7dd
Platform Intel DQ77KB motherboard, Q77 Express chipset w/Pulse-Eight USB adapter

**Comment by opdenkamp** [comment]
Fixed in master (though a bit differently)
