### ISSUE TITLE
exc_bad_access on OSX

### ISSUE THREAD

**Issue by RSully** [Pulse-Eight/libcec#150]
Using 3.0.1 I get an EXC_BAD_ACCESS using `DetectAdapters` (with last param false) or `Open`. If I call `DetectAdapters` with last param true, it does not trigger it (but then as soon as I `Open` it does).

Same code works fine using 2.2.0. 

Edit: on 10.11.1, installed libcec via homebrew

**Comment by RSully** [comment]
Isolated the libcec code from my app into this single file: https://gist.github.com/RSully/ff40878b9b1311f20c49

Compiled/linked against 3.0.1's dylib. When ran it produces an exc_bad_access on line 50 in `DetectAdapters`.

**Comment by opdenkamp** [comment]
can you run in a debugger like gdb and provide a backtrace please

**Comment by opdenkamp** [comment]
reported on irc to be fixed by @RSully
