### ISSUE TITLE
cec-client broken on OSX (homebrew)

### ISSUE THREAD

**Issue by RSully** [Pulse-Eight/libcec#151]
See discussion at homebrew/homebrew#45359.

**Comment by opdenkamp** [comment]
cec-client does not have the path to the library compiled it. it's just loading the .so from your path like any other binary. if you use a non-standard path (one that's not in the default LD library path), then you must specify the search path (on Linux):
```sh
LD_LIBRARY_PATH="/directory/of/the/lib" cec-client -i
```

not sure if it's the same on OS X and dyloading, but it'll be similar.
