### ISSUE TITLE
forcing openelec to switch hdmi port on AVR at boot

### ISSUE THREAD

**Issue by tomismrkolj** [Pulse-Eight/libcec#152]
Hi,

is there a way that kodi switches AVR's hdmi source from rpi2 to non-cec stb at boot?
I know it can be done by cec-client in script, however that breaks functionality of kodi cec client.

tnx
tomi

**Comment by opdenkamp** [comment]
No, this is not allowed by HDMI-CEC, so this is not included in any high level implementation. You could do this with a script indeed and it would work with most TVs that I've seen, but it's officially not allowed.
