### ISSUE TITLE
volume control not working over CEC

### ISSUE THREAD

**Issue by cvetters** [Pulse-Eight/libcec#154]
Hi, i want to control the volume of Kodi with the remote of my Samsung TV. Everything works fine, like channel up, down or navigation buttons. Only the volume will not work.
Kodi runs on a raspberry pi 2.

Is the problem the TV, Kodi or the RasperryPi?

**Comment by opdenkamp** [comment]
This is not supported by HDMI-CEC unfortunately. You can only control the volume of an audio sink (e.g. AVR)
