### ISSUE TITLE
Switch to 3D mode

### ISSUE THREAD

**Issue by Slion** [Pulse-Eight/libcec#167]
Is there a way to tell the TV to switch to 3D mode over CEC?
Notably with a Philips TV 55PFL7606K?

**Comment by popcornmix** [comment]
3D signalling doesn't use CEC so no.

**Comment by Slion** [comment]
How is it done then?

**Comment by popcornmix** [comment]
This isn't the place for non-CEC related questions.

**Comment by opdenkamp** [comment]
in infoframes. you can read all about it in HDMI 1.4b or newer ;-)
closing this ticket since it's indeed not possible to do this via CEC

**Comment by Slion** [comment]
Thanks for the pointers.
