### ISSUE TITLE
Kodi blocking port on Raspberry Pi

### ISSUE THREAD

**Issue by spectrokid** [Pulse-Eight/libcec#173]
I am using the OSMC distribution which has full buildt-in CEC support on a Raspberry 2.
 ` osmc@osmc:~$ cec-client -i
libCEC version: 2.1.4, host: arm-unknown-linux-gnueabihf, features: 'P8 USB' 'P8 USB detect', compiled on: Thu Aug  7 18:08:13 UTC 2014 by buildd@hoiby.debian.org on Linux 3.15-trunk-armmp-lpae (armv7l)
osmc@osmc:~$`

However, I want to send my own CEC commands independent from Kodi.  Even if I shut down Kodi, I still get : `  osmc@osmc:~$ sudo cec-client -l`
`   Found devices: NONE  `

Is there a way I can see if another process is "sitting" on the RPI port?
 
` osmc@osmc:~$ sudo cec-client -b COM RPI
using base device '0'
No device type given. Using 'recording device'
CEC Parser created - libCEC version 2.1.4
opening a connection to the CEC adapter...
DEBUG:   [               1]     unregistering all CEC clients
DEBUG:   [               2]     Broadcast (F): osd name set to 'Broadcast'
ERROR:   [            3505]     error opening serial port 'RPI': No such file or directory
  ` 

I do not have a ` /dev/ttyACM  ` on my raspberry.

**Comment by opdenkamp** [comment]
libCEC 2.1.4 is no longer supported. please upgrade your distribution to include libCEC 3.0.1.
