### ISSUE TITLE
raspbian and libudev.h not found?

### ISSUE THREAD

**Issue by snipiba** [Pulse-Eight/libcec#182]
USBCECAdapterDetection.cpp:62:21: fatal error: libudev.h: Adresár alebo súbor neexistuje
 #include <libudev.h>

**Comment by opdenkamp** [comment]
then you didn't follow the instructions for the raspberry pi in the readme file: https://github.com/Pulse-Eight/libcec/blob/141caf25e3c5a1fa709b052535185ba1ca3469ad/README.md
