### ISSUE TITLE
Update binaries available on website

### ISSUE THREAD

**Issue by gritstub** [Pulse-Eight/libcec#189]
This is a feature request for updated binaries, in particular for Windows.

The latest that I can find is v3.0.0 from the blog on May 13th, 2015 [1], while the official website has v2.2.0 [2]

Is this available somewhere else?

[1] http://blog.pulse-eight.com/2015/05/13/libcecv3-released/
[2] http://packages.pulse-eight.net/

Thanks!

**Comment by wingrunr21** [comment]
This would be nice given that there were a few bug fixes in 3.0.1 that related to LG tvs.

**Comment by afalout** [comment]
+1 for updated binaries. Windows 10 related updates would be of great help - #190 #130 etc. Thanks.

**Comment by CyberMonk** [comment]
Throwing in another request for updated Windows binaries to be posted; looks like 3.1.0 should be available, buy only 3.0.0 listed on site.

**Comment by opdenkamp** [comment]
the binaries will be updated with the 4.0.0 release, planned for this week

**Comment by afalout** [comment]
Cant find 4.0.0 release mentioned - was it updated? Thenks

**Comment by afalout** [comment]
Looks like this issue needs to be reopened as binaries are still not available. Thanks.
