### ISSUE TITLE
ubuntu modemmanager  issue

### ISSUE THREAD

**Issue by 9000h** [Pulse-Eight/libcec#193]
the Ubuntu ModemManager is trying to open the serial port /dev/ttyACM0 and as this is no modem an error get logged, to avoid this a udev rule can be used to prevent this
```
# Ubuntu ModemManager should ignore /dev/ttyACM0  
SUBSYSTEM=="usb", ENV{ID_VENDOR_ID}=="2548", ENV{ID_MODEL_ID}=="1002" ENV{ID_MM_DEVICE_IGNORE}="1"
```

**Comment by opdenkamp** [comment]
ah nice, I'll see if I can get that hooked up in our .deb

**Comment by UEckhardt** [comment]
I had nearly the same problem on a OpenSuSE 13.2, but also mtp-probe tried to access the serial port. To solve this I have extended the above udev rule and installed this rule as /etc/udev/rules.d/20-libcec.rules
```
# ModemManager and mtp probe should ignore /dev/ttyACM0  
ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="2548",  ATTRS{idProduct}=="1002", ENV{ID_MM_DEVICE_INORE}="1", ENV{MTP_NO_PROBE}="1"
```
