### ISSUE TITLE
Trouble with TX commands

### ISSUE THREAD

**Issue by thutson** [Pulse-Eight/libcec#196]
Working from an RPi, I have no problem turning a TV on and off using 
`echo "on 0" | cec-client -s` 
and 
`echo "standby 0" | cec-client -s`
but when I try to use any TX code I get no response and nothing of significance in the logs. The TV is a Vizio and the command to put in standby I am trying is
`echo "tx 10 36" | cec-client -s`
Any ideas why the preboxed commands work but not the TX?

**Comment by asulkowski** [comment]
I have the same problem.  Most of the "preboxed" commands work.  No TX commands work.

**Comment by opdenkamp** [comment]
the syntax is:
`echo "tx 10:36" | cec-client -s`
