### ISSUE TITLE
Cannot power on/off laptop monitor with LCD control board?

### ISSUE THREAD

**Issue by usherfu** [Pulse-Eight/libcec#206]
Hi, 
I have been working on a small pet project, which connects Raspberry PI to a LCD control board and monitor.   The monitor is essentially taken from an unused Lenovo laptop.      The LCD control board is similar to this one (http://www.ebay.com/itm/M-NT68676-2A-HDMI-DVI-VGA-Audio-LCD-LED-Screen-Controller-Board-Diy-Monitor-Kit-/110977522562). 

After installign libCEC on Raspberry PI, I tried following command

pi@hostname ~ $ cec-client -s -l
libCEC version: 3.1.0, git revision: libcec-3.1.0+5-6d68d21, compiled on Fri Mar 11 23:14:41 UTC 2016 by pi@mirror on Linux 4.1.18-v7+ (armv7l), features: P8_USB, DRM, P8_detect, randr, RPi
Found devices: 1

device:              1
com port:            RPI
vendor id:           2708
product id:          1001
firmware version:    1
type:                Raspberry Pi

Nothing happened when trying to switch on/off with following commands:

echo "standby 1" | cec-client -s 
echo "on 1" | cec-client -s

I also tried to run above commands with 0 instead of 1, and got the same result (nothing happened).

I am wondering if it is simply because the LCD controller board does NOT support, (in which case how can I validate?), or do I need the CEC Adapter (such as https://www.pulse-eight.com/p/104/usb-hdmi-cec-adapter)? Or any other advice?

Much appreciated!
Thanks!

**Comment by opdenkamp** [comment]
Sorry for the delay. It's highly unlikely that that screen supports CEC. You can test this with this cec-client command: `poll 0`. If the poll gets acked then it does support CEC, and if not, then it doesn't.

alternatively, you can use `scan` to make cec-client scan for devices

The parameter `1` should be `0` btw, which is the TV's address
