### ISSUE TITLE
Issue with Python "Command Callback"

### ISSUE THREAD

**Issue by TarteFramboise** [Pulse-Eight/libcec#207]
Hi,

I have modified the pyCecClient.py to have a command callback, my program runs fine, but the callback is never triggered... File is attached.

[pyCecClient2.py.zip](https://github.com/Pulse-Eight/libcec/files/174513/pyCecClient2.py.zip)

Is the Command Callback supposed to be working ? What can be wrong with my setup ?

Regards, JP

**Comment by opdenkamp** [comment]
It's working. I've added example code to https://github.com/Pulse-Eight/libcec/blob/master/src/pyCecClient/pyCecClient.py
