### ISSUE TITLE
Errors while trying to debugin VS 2013 Ultimate

### ISSUE THREAD

**Issue by appup93** [Pulse-Eight/libcec#216]
I am getting a lot of errors in VS 2013 while trying to debug the project. Most of them are related to Intellisense(identifier uint8_t,uint16_t,uint32_t is undefined) while the other issue is that Properties/Assemblyinfo.cs file is missing. Please suggest a way to solve the issues.

**Comment by opdenkamp** [comment]
as indicated in email: it's a problem with your build environment (missing prerequisites)
