### ISSUE TITLE
LIBCEC SWITCHING TV

### ISSUE THREAD

**Issue by Seb85** [Pulse-Eight/libcec#221]
Hello,

I have a concern since I moved from v2.2 to the 3. It is not possible to change the source on my samsung tv with the following command:

echo "tx 4F 82 10 00" | cec-client -s

This command has no effect .

Thanks for your help

**Comment by santi6291** [comment]
Hi @Seb85 I never used V2 but seems like V3 the tx logic should be colon separated instead
`echo "tx 4F:82:30:00" | cec-client -s`

https://github.com/Pulse-Eight/libcec/issues/196

**Comment by Seb85** [comment]
It works . It was a stupidity .. Thank you saved my life!
