### ISSUE TITLE
C++ Compiler Not Found Windows 

### ISSUE THREAD

**Issue by appup93** [Pulse-Eight/libcec#222]
Hi

When i run the visual-cmd script i am getting the following error.
I have installed c/c++ support for visual studio. Any other C++ compiler items i need to install? 

-- Performing Test SUPPORTS_CXX11
-- Performing Test SUPPORTS_CXX11 - Failed

**Comment by Slion** [comment]
Make sure all the prerequisites are meet. Not such an error here.

**Comment by opdenkamp** [comment]
Please follow the instruction in https://github.com/Pulse-Eight/libcec/blob/master/README.md
