### ISSUE TITLE
[Suggestion] Have libcec* provide package libcec3v4

### ISSUE THREAD

**Issue by ProfessorKaos64** [Pulse-Eight/libcec#224]
I've had a few cases where one application (e.g. Kod) use libcec3, and that is much preferred, and some applications request libcec3v4 in some projects. Can this be avoided by specifying in debian/control a `Provides: libcec3v4` to avoid this? Just some thoughts.

**Comment by opdenkamp** [comment]
This `libcec3v4` is something that got created by Debian package maintainers. They've created this mess... I'd added it earlier but forgot to commit it. Done now, thanks
