### ISSUE TITLE
version.h file not found error

### ISSUE THREAD

**Issue by PAV1THRA** [Pulse-Eight/libcec#227]
while running the sample program getting error "cannot open file version.h : No such file or directory exists" .
This is the output.
C:\Python27>pip install cec
Collecting cec
  Using cached cec-0.2.5.tar.gz
Installing collected packages: cec
  Running setup.py install for cec ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools
, tokenize;__file__='c:\\users\\unameit\\appdata\\local\\temp\\pip-build-cfwkhz\
\cec\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().re
place('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\unameit\appda
ta\local\temp\pip-m0b6sp-record\install-record.txt --single-version-externally-m
anaged --compile:
    running install
    running build
    running build_ext
    building 'cec' extension
    creating build
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo
/Ox /MD /W3 /GS- /DNDEBUG -Iinclude -Ic:\python27\include -Ic:\python27\PC /Tpce
c.cpp /Fobuild\temp.win32-2.7\Release\cec.obj
    cec.cpp
    c:\python27\include\libcec\cectypes.h(37) : fatal error C1083: Cannot open i
nclude file: 'version.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BI
N\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\
\users\\unameit\\appdata\\local\\temp\\pip-build-cfwkhz\\cec\\setup.py';exec(com
pile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __f
ile__, 'exec'))" install --record c:\users\unameit\appdata\local\temp\pip-m0b6sp
-record\install-record.txt --single-version-externally-managed --compile" failed
 with error code 1 in c:\users\unameit\appdata\local\temp\pip-build-cfwkhz\cec\

**Comment by opdenkamp** [comment]
that must be a packaging problem from whoever packaged it, who forgot to include that file. it's auto generated during the build process.

there was a version some time ago that didn't have it included in the installer, which is perhaps used for this package.

please contact the maintainer of the source that you're using to include version.h
