### ISSUE TITLE
Compilation failure on RPi2 following the guide outlined in the readme

### ISSUE THREAD

**Issue by jkiddo** [Pulse-Eight/libcec#228]
I'm having issues compiling the library as described. It stalls in the step of executing 'make -j4'

osmc@osmc:~/libcec/build$ make -j4
Scanning dependencies of target cec
[  2%] [  8%] [  8%] [ 10%] Building CXX object src/libcec/CMakeFiles/cec.dir/LibCEC.cpp.o
Building CXX object src/libcec/CMakeFiles/cec.dir/LibCECC.cpp.o
Building CXX object src/libcec/CMakeFiles/cec.dir/CECClient.cpp.o
Building CXX object src/libcec/CMakeFiles/cec.dir/CECProcessor.cpp.o
[ 13%] Building CXX object src/libcec/CMakeFiles/cec.dir/adapter/RPi/RPiCECAdapterDetection.cpp.o
/home/osmc/libcec/src/libcec/adapter/RPi/RPiCECAdapterDetection.cpp:40:47: fatal error: interface/vmcs_host/vc_cecservice.h: No such file or directory
 #include <interface/vmcs_host/vc_cecservice.h>
                                               ^
compilation terminated.

**Comment by opdenkamp** [comment]
The header path is set incorrectly, or you didn't install them.

The instructions from the README.md file work when using the official Raspbian distribution. If they don't work for another distribution, then you need to ask for help on it's forums or ask the maintainer(s).
