### ISSUE TITLE
Samsung ue40es6300uxxu Exit button problem

### ISSUE THREAD

**Issue by Pintglass** [Pulse-Eight/libcec#229]
I have my rpi2 connected to my Samsung ue40es6300uxxu TV which has worked perfectly since i set it up, but within the last few weeks the exit button on the remote has stopped working, the exit button on the remote works within the TV menus but no longer works with cec, it used to function as the back key in kodi.
I'm running openelec 6.0.3 with a libcec version of 3.0.1.
I'm not sure what has changed as i have not changed anything in my setup and as far as i know no upgrades have taken place.
I have run cec-client over a ssh connection to test if i get anything from the exit button but nothing is being received, so maybe my TV has stopped passing that particular key all other buttons work fine.

**Comment by opdenkamp** [comment]
cec-client won't receive any keys unless you issue the `as` command, to make the adapter the active source.

I've just tested the exit button on an older Samsung with the current code in master, soon to be released as v4.0.0, and I'm not seeing any issues with this key. I also haven't heard about any changes in more recent models related to this key.

If you still have issues after upgrading to libCEC 4.0.0, please upload a log and I'll reopen this ticket. It could be a problem on Kodi's side.
