### ISSUE TITLE
Following error - Configuring Error

### ISSUE THREAD

**Issue by sameershah23** [Pulse-Eight/libcec#236]
pi@raspberrypi:~/libcec/build $ cmake -DCMAKE_CXX_COMPILER=g++-4.8 -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=1 ..
-- The CXX compiler identification is GNU 4.8.4
-- Check for working CXX compiler: /usr/bin/g++-4.8
-- Check for working CXX compiler: /usr/bin/g++-4.8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- git found: libcec-3.1.0+5-6d68d21~dirty
-- Configured features:
-- Pulse-Eight CEC Adapter:                yes
-- Pulse-Eight CEC Adapter detection:      yes
-- xrandr support:                         yes
-- Raspberry Pi support:                   yes
-- TDA995x support:                        no
-- Exynos support:                         no
-- DRM support:                            yes
-- Python support:                         version 3.4.2 (3.4)
-- lib info: git revision: libcec-3.1.0+5-6d68d21~dirty, compiled on Fri Jul 29 01:09:58 UTC 2016 by pi@raspberrypi on Linux 4.4.13-v7+ (armv7l), features: P8_USB, DRM, P8_detect, randr, RPi
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
RPI_BCM_HOST
    linked by target "cec" in directory /home/pi/libcec/src/libcec
RPI_VCHIQ_ARM
    linked by target "cec" in directory /home/pi/libcec/src/libcec
RPI_VCOS
    linked by target "cec" in directory /home/pi/libcec/src/libcec

-- Configuring incomplete, errors occurred!
See also "/home/pi/libcec/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/libcec/build/CMakeFiles/CMakeError.log".

**Comment by opdenkamp** [comment]
that's because you're not following the instructions from https://github.com/Pulse-Eight/libcec/blob/master/README.md for the Raspberry Pi
