### ISSUE TITLE
Set Default Name for CEC

### ISSUE THREAD

**Issue by Huskynarr** [Pulse-Eight/libcec#238]
Im not sure, if libcec or cec-client(platform) set the Name.
But always on a new Connection would be set the OSD Name to "CEC-Tester".
How i can change that permant?

**Comment by Huskynarr** [comment]
Have fix it.

Have edit: _libcec/src/cec-client/cec-client.cpp_ 

And change line 1245:
` snprintf(g_config.strDeviceName, 13, "mainframe");`

After that, i have compiled new.
Then restart "make".

**Comment by opdenkamp** [comment]
yup, it's hardcoded in cec-client because it's mainly a debugging client and example application for libCEC, but quite easy to change and recompile indeed.
