### ISSUE TITLE
Installing HDMI CEC with Windows Embedded Standard

### ISSUE THREAD

**Issue by PAV1THRA** [Pulse-Eight/libcec#248]
Hi,

I am unable to communicate with the TV using HDMI CEC connected with the Windows Embedded Standard OS.

Could you please tell whether HDMI CEC supports the Windows Embedded Standard OS.

**Comment by opdenkamp** [comment]
Yes, but the driver to communicate with the adapter is not installed on Windows Embedded by default, as it tries to keep it's footprint as small as possible.

If you add this driver when installing Windows, then it'll install the required files:
https://dl.dropboxusercontent.com/u/59212404/driver.iso or
https://dl.dropboxusercontent.com/u/59212404/driver.zip

**Comment by bcoady** [comment]
The link is dead. Can you re-post where to get the driver for Windows Embedded.
