### ISSUE TITLE
cec-client commands on windows 10

### ISSUE THREAD

**Issue by blkbam** [Pulse-Eight/libcec#249]
Is anyone using the client tool to send command line commands on Windows 10? I may be doing things incorrectly but I can't get cec-client to process any commands I give it.  All of the command line syntax I can find references RaspberryPi and Linux syntax. I have the driver and tray app set up and responding properly though I can't get the command line to do anything except list the device.

**Comment by opdenkamp** [comment]
The commands on Linux and Windows are the same, except that you must omit any " in the echo command if you're looking at examples for Linux. So to power on the TV:
`echo as | cec-client.exe -s`
