### ISSUE TITLE
Raspberry pi build wont make

### ISSUE THREAD

**Issue by scoobyd00** [Pulse-Eight/libcec#254]
I can get this far with the make -j4 command then it crashes....

[ 13%] Building CXX object src/libcec/CMakeFiles/cec.dir/adapter/RPi/RPiCECAdapterDetection.cpp.o
/home/pi/libcec/src/libcec/adapter/RPi/RPiCECAdapterDetection.cpp:40:47: fatal error: interface/vmcs_host/vc_cecservice.h: No such file or directory
 #include <interface/vmcs_host/vc_cecservice.h>
                                               ^
compilation terminated.
src/libcec/CMakeFiles/cec.dir/build.make:146: recipe for target 'src/libcec/CMakeFiles/cec.dir/adapter/RPi/RPiCECAdapterDetection.cpp.o' failed
make[2]: *** [src/libcec/CMakeFiles/cec.dir/adapter/RPi/RPiCECAdapterDetection.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:227: recipe for target 'src/libcec/CMakeFiles/cec.dir/all' failed
make[1]: *** [src/libcec/CMakeFiles/cec.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

Any ideas why?

**Comment by opdenkamp** [comment]
because you didn't follow the instructions from the readme.md file to the letter..

**Comment by scoobyd00** [comment]
I followed these to the letter...

sudo apt-get update
sudo apt-get install cmake liblockdev1-dev libudev-dev libxrandr-dev python-dev swig
cd
git clone https://github.com/Pulse-Eight/platform.git
mkdir platform/build
cd platform/build
cmake ..
make
sudo make install
cd
git clone https://github.com/Pulse-Eight/libcec.git
mkdir libcec/build
cd libcec/build
cmake -DRPI_INCLUDE_DIR=/opt/vc/include -DRPI_LIB_DIR=/opt/vc/lib ..
make -j4
sudo make install
sudo ldconfig

Could you help me whats wrong?

**Comment by opdenkamp** [comment]
The instructions apply to Raspbian, which install headers and libs in /opt/vc
If you distribution does something else, please ask it's maintainers

**Comment by scoobyd00** [comment]
Thankyou for the information, installed everything into /opt/vc on my build and it successfully compiled and is working great.
