### ISSUE TITLE
CEC.return (Samsung) not forwarded when pressed multiple times in EventGhost

### ISSUE THREAD

**Issue by NKnusperer** [Pulse-Eight/libcec#260]
At my first try the `CEC.return (Samsung)` key was not forwarded at all to EventGhost but every press was visible in the test client. However after looking at #128 I updated `EventGhost/plugins/libCEC/__init__.py`  to the current master version.  Now the key is forwarded to EventGhost but only once, if pressed multiple times in a row any further event is not forwarded until another key is pressed. Then it works one time again.
Other keys don't have this issue.
I think this must be some bug in the EventGhost plugin because in the test client everything looks fine.
OS is Windows 10 x64.
1. Press `CEC.return` - forwarded
2. Press `CEC.return` - not forwarded
3. Press `CEC.up` - forwarded
4. Press `CEC.return` - forwarded
5. Press `CEC.return` - not forwarded

Btw: Will there be any new official Windows build available?
The current one is 3.0.0 but on GitHub there is already a 4.0.

**Comment by opdenkamp** [comment]
I've just tested this with pyCecClient.py and I'm not seeing any issues. You can download the latest binary here for the moment: https://dl.dropboxusercontent.com/u/59212404/libCEC-4.0.0.exe
The binaries on the website will be updated soon
