### ISSUE TITLE
Python bindings for OS X 10.12

### ISSUE THREAD

**Issue by BrendanNeufeld** [Pulse-Eight/libcec#267]
Hey, I am trying to integrate HDMI CEC component for home-assistant on OX 10.12. The error I get is `ERROR (Thread-1) [homeassistant.components.hdmi_cec] libcec must be installed` I tried installing  libcec whith brew as well as by the build method mentioned in your OS X instructions.

I feel like the Python bindings are failing for the latest version of OS X (v10.12).

**Comment by opdenkamp** [comment]
The Python binding is working when using the example code that we provide.

I suspect that the binding for home assistant will need updating because of some API changes between libCEC 3 and 4.

Please contact it's maintainer
