### ISSUE TITLE
Please add support  to build the proyect in Microsoft Visual Studio 14.0

### ISSUE THREAD

**Issue by asueroaltimetrik** [Pulse-Eight/libcec#269]
Please add the functionality to build the project and create installer in Microsoft Visual Studio 14.0

**Comment by opdenkamp** [comment]
You should be able to generate the project files for VS14 by changing this line: https://github.com/Pulse-Eight/libcec/blob/master/windows/visual-studio.cmd#L9

Creating an installer needs some changes in this script: https://github.com/Pulse-Eight/libcec/blob/master/windows/create-installer.cmd#L19

I'll look into creating an installer without editing scripts later.

**Comment by opdenkamp** [comment]
I've just checked with VS2017, and everything seems to be working correctly (when editing the VS version in the script still)
