### ISSUE TITLE
Volume Down Not Working

### ISSUE THREAD

**Issue by grizzlyjere** [Pulse-Eight/libcec#272]
Hi,

I'm having a problem where my system is increasing in volume with the VolumeDown command is sent.   In looking at the raw data being sent, VolumeDown was sending 15:44:41, which is Volume Up if I'm correct in my understanding (I'm new to the world of HDMI CEC).

In digging around the code, i appears there could be a copy/paste issue in CECBusDevice.cpp
```
bool CCECBusDevice::TransmitVolumeDown(const cec_logical_address source, bool bSendRelease /* = true */)
{
  bool retval = TransmitKeypress(source, CEC_USER_CONTROL_CODE_VOLUME_UP);
  if (bSendRelease && retval)
    retval &= TransmitKeyRelease(source);
  return retval;
}
```

I believe CEC_USER_CONTROL_CODE_VOLUME_UP should be CEC_USER_CONTROL_CODE_VOLUME_DOWN, correct?

**Comment by michaelarnauts** [comment]
I have also noticed this. I think this used to work fine in libcec3.
