### ISSUE TITLE
Not working on RasPi 3

### ISSUE THREAD

**Issue by spacelego** [Pulse-Eight/libcec#273]
Fresh install of 2016-11-25-raspbian-jessie-lite

sudo apt-get install cec-utils

...went ok, seems like I got v4.0...

libCEC version: 4.0.0, git revision: libcec-4.0.0-3, compiled on Sat  3 Dec 23:33:33 UTC 2016 by pi@raspi-rtsp on Linux 4.4.34-v7+ (armv7l), features: P8_USB, DRM, P8_detect, randr

...anything I try to run I get...

autodetect FAILED

TV shows "raspberry"
Tried different cables
Not sure what to do.

**Comment by popcornmix** [comment]
I don't believe that version of libcec comes from either upstream raspbian, or the raspberry pi repo.
I suspect you have added an additional repo that contained this (perhaps pipplware or Michael Gorven's kodi repo?)
The issue probably needs to be reported with them first, in case they have made a mistake in configuring libcec.

**Comment by opdenkamp** [comment]
Try again with libCEC built from current master. If this still occurs, please send me the output of `cec-client -d 31 -l`
