### ISSUE TITLE
Remote buttons not working on TCL TV

### ISSUE THREAD

**Issue by jbmfg** [Pulse-Eight/libcec#277]
Im betting this is an issue with my TV rather than libcec.  

Command echo "standby 0" | cec-client -s -p 2 does work to put my tv into standby so i know cec is working.  However no remote button presses are registered.  Not sure what to do to troubleshoot

Raspberry pi with rasplex installed

echo "standby 0" | cec-client -s -p 2
using HDMI port '2'
opening a connection to the CEC adapter...
DEBUG:   [             808]	Broadcast (F): osd name set to 'Broadcast'
DEBUG:   [             811]	InitHostCEC - vchiq_initialise succeeded
DEBUG:   [             812]	InitHostCEC - vchi_initialise succeeded
DEBUG:   [             813]	InitHostCEC - vchi_connect succeeded
DEBUG:   [             816]	logical address changed to Free use (e)
DEBUG:   [             817]	Open - vc_cec initialised
NOTICE:  [             818]	connection opened
DEBUG:   [             823]	<< Broadcast (F) -> TV (0): POLL
DEBUG:   [             824]	initiator 'Broadcast' is not supported by the CEC adapter. using 'Free use' instead
TRAFFIC: [             824]	<< e0
DEBUG:   [             826]	processor thread started
DEBUG:   [             886]	>> POLL sent
DEBUG:   [             886]	TV (0): device status changed into 'present'
DEBUG:   [             886]	<< requesting vendor ID of 'TV' (0)
TRAFFIC: [             887]	<< e0:8c
WARNING: [            1140]	unhandled response received: opcode=4 initiator=e destination=0 response=0
TRAFFIC: [            1141]	>> 0e:00:8c:00
DEBUG:   [            1143]	marking opcode 'give device vendor id' as unsupported feature for device 'TV'
DEBUG:   [            1143]	expected response received (87: device vendor id)
NOTICE:  [            1143]	registering new CEC client - v3.0.1
DEBUG:   [            1143]	detecting logical address for type 'recording device'
DEBUG:   [            1143]	trying logical address 'Recorder 1'
DEBUG:   [            1143]	<< Recorder 1 (1) -> Recorder 1 (1): POLL
TRAFFIC: [            1143]	<< 11
TRAFFIC: [            1414]	<< 11
DEBUG:   [            1684]	>> POLL not sent
DEBUG:   [            1685]	using logical address 'Recorder 1'
DEBUG:   [            1685]	Recorder 1 (1): device status changed into 'handled by libCEC'
DEBUG:   [            1685]	Recorder 1 (1): power status changed from 'unknown' to 'on'
DEBUG:   [            1685]	Recorder 1 (1): vendor = Pulse Eight (001582)
DEBUG:   [            1685]	Recorder 1 (1): CEC version 1.4
DEBUG:   [            1685]	AllocateLogicalAddresses - device '0', type 'recording device', LA '1'
DEBUG:   [            1687]	logical address changed to Recorder 1 (1)
DEBUG:   [            1687]	Recorder 1 (1): osd name set to 'CECTester'
DEBUG:   [            1688]	Recorder 1 (1): menu language set to 'eng'
DEBUG:   [            1690]	GetPhysicalAddress - physical address = 2000
DEBUG:   [            1690]	AutodetectPhysicalAddress - autodetected physical address '2000'
DEBUG:   [            1690]	Recorder 1 (1): physical address changed from ffff to 2000
DEBUG:   [            1690]	<< Recorder 1 (1) -> broadcast (F): physical adddress 2000
TRAFFIC: [            1690]	<< 1f:84:20:00:01
NOTICE:  [            1841]	CEC client registered: libCEC version = 3.0.1, client version = 3.0.1, firmware version = 1, logical address(es) = Recorder 1 (1) , physical address: 2.0.0.0, git revision: 426d013, compiled on Mon Nov  7 15:57:36 UTC 2016 by docker@5b37fa058f49 on Linux 4.4.0-45-generic (x86_64), features: P8_USB, P8_detect, 'RPi'
DEBUG:   [            1841]	<< Recorder 1 (1) -> TV (0): OSD name 'CECTester'
TRAFFIC: [            1842]	<< 10:47:43:45:43:54:65:73:74:65:72
DEBUG:   [            2173]	<< requesting power status of 'TV' (0)
TRAFFIC: [            2173]	<< 10:8f
TRAFFIC: [            2264]	>> 01:46
DEBUG:   [            2264]	<< Recorder 1 (1) -> TV (0): OSD name 'CECTester'
TRAFFIC: [            2265]	<< 10:47:43:45:43:54:65:73:74:65:72
DEBUG:   [            2265]	>> TV (0) -> Recorder 1 (1): give osd name (46)
TRAFFIC: [            2626]	>> 01:90:00
DEBUG:   [            2626]	TV (0): power status changed from 'unknown' to 'on'
DEBUG:   [            2626]	>> TV (0) -> Recorder 1 (1): report power status (90)
DEBUG:   [            2627]	expected response received (90: report power status)
DEBUG:   [            2628]	<< requesting vendor ID of 'TV' (0)
DEBUG:   [            2628]	'give device vendor id' is marked as unsupported feature for device 'TV'
NOTICE:  [            2628]	<< putting 'TV' (0) in standby mode
TRAFFIC: [            2629]	<< 10:36
WARNING: [            2685]	unhandled response received: opcode=4 initiator=1 destination=0 response=0
DEBUG:   [            2776]	unregistering all CEC clients
NOTICE:  [            2776]	unregistering client: libCEC version = 3.0.1, client version = 3.0.1, firmware version = 1, logical address(es) = Recorder 1 (1) , physical address: 2.0.0.0, git revision: 426d013, compiled on Mon Nov  7 15:57:36 UTC 2016 by docker@5b37fa058f49 on Linux 4.4.0-45-generic (x86_64), features: P8_USB, P8_detect, 'RPi'
DEBUG:   [            2776]	Recorder 1 (1): power status changed from 'on' to 'unknown'
DEBUG:   [            2776]	Recorder 1 (1): vendor = Unknown (000000)
DEBUG:   [            2776]	Recorder 1 (1): CEC version unknown
DEBUG:   [            2776]	Recorder 1 (1): osd name set to 'Recorder 1'
DEBUG:   [            2776]	Recorder 1 (1): device status changed into 'unknown'
DEBUG:   [            2777]	unregistering all CEC clients
DEBUG:   [            2831]	UnregisterLogicalAddress - releasing previous logical address
Segmentation fault (core dumped)

**Comment by greedysquid** [comment]
I believe I have the same problem/symptom.

Panasonic TX-P42G20B TV
Raspberry Pi B+ v1.2
Clean install of 2016-11-25-raspbian-jessie-lite.zip
Then install CEC utilities: `sudo apt-get cec-utils`

My goal is to use the above RaspberryPi to initially monitor and then interact with CEC traffic.
CEC is already working on my setup; the TV can control an amp, DVD player and another Kodi RaspberryPi.

Running `cec-client` successfully initialises and auto-configures itself on to the CEC bus.

`pi@raspberrypi:~ $ cec-client
No device type given. Using 'recording device'
CEC Parser created - libCEC version 3.0.1
no serial port given. trying autodetect:
 path:     Raspberry Pi
 com port: RPI

opening a connection to the CEC adapter...
DEBUG:   [             135]     Broadcast (F): osd name set to 'Broadcast'
DEBUG:   [             140]     InitHostCEC - vchiq_initialise succeeded
DEBUG:   [             141]     InitHostCEC - vchi_initialise succeeded
DEBUG:   [             142]     InitHostCEC - vchi_connect succeeded
DEBUG:   [             145]     logical address changed to Free use (e)
DEBUG:   [             147]     Open - vc_cec initialised
NOTICE:  [             149]     connection opened
DEBUG:   [             151]     << Broadcast (F) -> TV (0): POLL
DEBUG:   [             151]     initiator 'Broadcast' is not supported by the CEC adapter. using 'Free use' instead
TRAFFIC: [             151]     << e0
DEBUG:   [             156]     processor thread started
DEBUG:   [             182]     >> POLL sent
DEBUG:   [             182]     TV (0): device status changed into 'present'
DEBUG:   [             182]     << requesting vendor ID of 'TV' (0)
TRAFFIC: [             182]     << e0:8c
TRAFFIC: [             391]     >> 0f:87:00:80:45
DEBUG:   [             391]     TV (0): vendor = Panasonic (008045)
DEBUG:   [             392]     expected response received (87: device vendor id)
DEBUG:   [             392]     replacing the command handler for device 'TV' (0)
NOTICE:  [             392]     registering new CEC client - v3.0.1
DEBUG:   [             392]     detecting logical address for type 'playback device'`

`NOTICE:  [            1572]     CEC client registered: libCEC version = 3.0.1, client version = 3.0.1, firmware version = 1, logical address(es) = Playback 3 (B) , physical address: 4.0.0.0,  compiled on Fri Jul  3 19:20:43 UTC 2015 by pbuilder@mgorven-pc.thefacebook.com on Linux 3.16.0-41-generic (armv7l), features: P8_USB, P8_detect, 'RPi'`

The above shows that the Pi is connected-to, and sending/receiving-on, the CEC bus. Manually sending a command (eg wakup DVD player) is also sucessful.

However, when pressing a button on the TV's remote nothing is seen in the output of cec-client.
A command is definately sent over the CEC bus - eg volup makes the amplifier change volume, and using a scope I can see corresponding traffic on the CEC pin of the Pi.

So, like @jbmfg who opened this issue (#277), I too do not see remote control button press events in the output from cec-client (from the current Raspian cec-utils package).

How to debug further?

**Comment by opdenkamp** [comment]
cec-client will not automatically make itself the active source on the CEC bus when started, so it won't receive any keys from the TV by default in most situations.

You have to tell cec-client to become active (the command `as`), then it'll work.
