### ISSUE TITLE
MegaChips MCDP2800 LSPCON  driver

### ISSUE THREAD

**Issue by 9000h** [Pulse-Eight/libcec#280]
is there any plan to support the MegaChips MCDP2800 LSPCON chip?

the new NUC6CAYH will also have it and CEC support should be possible as there is support in the Bios
https://www-ssl.intel.com/content/dam/support/us/en/documents/boardsandkits/NUC6CAYB_TechProdSpec.pdf

there are also some motherboards from Gigabyte and Asrock with this DP>HDMI chip out

there is probably the latest drm-intel driver needed as the hdmi-cec is tunneled via DP AUX
https://cgit.freedesktop.org/drm-intel/log/?qt=grep&q=LSPCON

on newer kernels the access to DP AUX is exposed via sys fs and also a device node is available

dmesg drm debug
[  407.559216] [drm:intel_dp_read_desc] DP branch: OUI 00-60-ad(NS) dev-ID MC2800 HW-rev 2.2 SW-rev 1.56

cat /sys/class/drm_dp_aux_dev/drm_dp_aux1/name 
DPDDC-B

cat  /sys/class/drm_dp_aux_dev/drm_dp_aux1/device/status 
connected

this is the related device
/dev/drm_dp_aux1

looks like there is way to talk with the chip
_____
cat /dev/drm_dp_aux1
?
 ??@ww????? `?Dp1.1`?MC2800"8cat: /dev/drm_dp_aux1: Input/output error
_____
```
i2cdetect -l
i2c-3	i2c       	DPDDC-A                         	I2C adapter
i2c-1	i2c       	i915 gmbus dpc                  	I2C adapter
i2c-4	i2c       	DPDDC-B                         	I2C adapter
i2c-2	i2c       	i915 gmbus misc                 	I2C adapter
i2c-0	i2c       	i915 gmbus dpb                  	I2C adapter

i2cdump -y 4 0x40
No size specified (using byte-data access)
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f    0123456789abcdef
00: 44 50 2d 48 44 4d 49 20 41 44 41 50 54 4f 52 04    DP-HDMI ADAPTOR?
10: a8 00 60 ad 00 00 00 00 00 00 00 00 00 88 0f 00    ?.`?.........??.
20: 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00    ..?.............
30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
40: 01 01 05 00 00 00 04 00 80 06 00 00 00 00 00 00    ???...?.??......
50: 00 01 00 00 01 22 00 03 00 00 00 01 00 00 00 00    .?..?".?...?....
60: 00 00 00 00 60 00 60 00 00 00 00 00 00 00 00 01    ....`.`........?
70: 00 00 00 01 00 03 00 03 00 00 00 00 00 01 00 00    ...?.?.?.....?..
80: 00 fa 00 00 00 00 00 22 37 01 00 0f 00 32 49 00    .?....."7?.?.2I.
90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
b0: 00 00 00 84 01 0a 00 70 01 00 00 00 00 00 00 00    ...???.p?.......
c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
d0: 00 00 00 00 00 00 00 00 00 08 00 00 00 be af 00    .........?...??.
e0: 00 01 01 00 00 00 00 e7 00 00 00 00 00 00 00 00    .??....?........
f0: 00 00 00 02 04 00 00 00 00 00 00 01 00 00 00 01    ...??......?...?

```

could be DP_DUAL_MODE_SLAVE_ADDRESS 0x40

**Comment by opdenkamp** [comment]
as far as I can tell from the docs, the pin is simply exposed by the chip and doesn't contain any logic, so it would have to be bitbanged by some kernel implementation and then be exposed to libCEC.
the new Linux in-kernel CEC implementation would be the right place to do this.

**Comment by 9000h** [comment]
there is a driver coming to the kernel soon
https://patchwork.freedesktop.org/project/intel-gfx/patches/?submitter=15857

**Comment by opdenkamp** [comment]
I'm sure that it'll use the new in-kernel framework then, for which there is a ticket here: https://github.com/Pulse-Eight/libcec/issues/67
