### ISSUE TITLE
Support for Allwinner A20?

### ISSUE THREAD

**Issue by copytco** [Pulse-Eight/libcec#285]
Hi, is support for A20 planned? It would be great if I could use this library on my Banana Pi.

**Comment by malard** [comment]
it is available as part of our commercial library

**Comment by copytco** [comment]
Where can I get it then?

**Comment by malard** [comment]
contact licensing@pulse-eight.com if you want to enquire about pricing, if this is for personal use then its probably not for you and we wont be able to support you i am sorry

**Comment by copytco** [comment]
It is a shame then, that A20 is not widely available, as Banana Pi's share is growing.
