### ISSUE TITLE
Problem with using the edid parsers in the Pulse8 adapter

### ISSUE THREAD

**Issue by gdachs** [Pulse-Eight/libcec#287]
@opdenkamp:
I think this [line](https://github.com/Pulse-Eight/libcec/blob/master/src/libcec/adapter/Pulse-Eight/USBCECAdapterCommunication.cpp#L671) and the equivalent lines in your Pulse8 adapter code are wrong, look at this [line](https://github.com/gdachs/libcec/blob/d591b4b84d85788c420b9a5ba3517dec6460a2b9/src/libcec/adapter/RainShadow/RainAdapterCommunication.cpp#L303) in my PR.
HAS => HAVE.
Additionally [this](https://github.com/Pulse-Eight/libcec/pull/286/files#diff-85d57347d02eb400fcada7e8100e3fec) is missing.

**Comment by opdenkamp** [comment]
the first one isn't a bug, because it's not configured by the cmake script. I've changed it anyway so it matches the other ones. will be pushed in a few

the other one was missing indeed, thanks.
