### ISSUE TITLE
OS X packaging via MacPorts

### ISSUE THREAD

**Issue by ctreleaven** [Pulse-Eight/libcec#295]
Wanted to let you know that libcec is available for Mac OS X via the MacPorts packaging system.  Unfortunately, I don't own compatible hardware so I haven't been able to test the software in an OS X environment.

https://www.macports.org/index.php

The project may wish to update docs/README.osx.md.

I'm not very familiar with cmake but did have some observations.

Apparently libcec requires C++11.  OS X, by default, only began to support C++11 with version 10.9.  There are ways to support C++11 on older OS versions, however, if the user really wants.  (https://trac.macports.org/wiki/LibcxxOnOlderSystems)  The MacPorts buildbots have verified that libcec builds successfully on OS X versions 10.9 through 10.12.

If available, libcec links to LibX11 and Xrandr.  I'm not clear what functionality that provides.

libcec also appears to require a version of Python3.  The MacPorts build will ensure that Python 3.4 is used.  The README does not mention this.  In addition, the build also appears to use swig-python to create python bindings.  This might also be mentioned.

**Comment by opdenkamp** [comment]
Thanks!

* the C++11 requirement is documented, but I'll add that it only got added in 10.9
* xrandr is used to read the sink's EDID, which is needed to determine the PC's HDMI physical address ("which HDMI input on the TV is used")
* I believe that Python 2.6 should work too, but it's only been tested on Windows
* I'll add the optional Swig dependency in the readme
