### ISSUE TITLE
How to find the hdmi source number ?

### ISSUE THREAD

**Issue by PAV1THRA** [Pulse-Eight/libcec#301]
Hi 

I am using the python version. Could anyone please tell me how to find the hdmi source number to which my TV is connected. Is there any specific command to get that information.

**Comment by opdenkamp** [comment]
If you're using Linux and X is running, then it'll be detected by libCEC automatically, assuming that it's started with the DISPLAY parameter set to point to the correct X instance.
e.g. `DISPLAY=":0" /path/to/your/python_script.py`

If you're using Windows, then you can't automatically detect it from within Python unfortunately.
