### ISSUE TITLE
Issue in switching the hdmi source from a program

### ISSUE THREAD

**Issue by PAV1THRA** [Pulse-Eight/libcec#302]
Hi 
While using the "as" command for switching ON the TV, the HDMI 1 is displayed by default. Is there any command to switch on the TV with different HDMI. (for ex: switch on the TV with the HDMI 2).

**Comment by opdenkamp** [comment]
You can try using the `-p` parameter (see `cec-client -h` for explanations for all parameters), but if libCEC can read the EDID of the TV, then it'll use the correct physical address which is in there. If you've connected the PC to HDMI 1 of the TV, then that's what it will use.

It's possible to overrule this with another physical address, but cec-client does not support this.
