### ISSUE TITLE
CECActivateSource Builtin Kodi command

### ISSUE THREAD

**Issue by Jooobs** [Pulse-Eight/libcec#310]
Hello

I would love to be able to use the CECActivateSource Builtin Kodi command on LibreELEC however it seems to be broken? There are various posts suggesting that it has been broken at times.
Basically I have been testing it via a Kodi keymap script, wanting to activate the Kodi HDMI source when a remote button is pressed but nothing happens - other builtin commands work fine in the script, but not the three CEC commands. I've tried all sorts of different syntax too.

Is this meant to work? I'm on LibreELEC version 7.0.2 using a new Pulse Eight on an Intel based machine.

If this has nothing to do with Pulse Eight / libCEC then I guess I'll raise it with Kodi directly?

The base requirement is to switch back to Kodi from my Chromecast without having to grab the AVR remote to swap inputs.

Julan

**Comment by opdenkamp** [comment]
Please raise a ticket on Kodi's trac: http://trac.kodi.tv/ because this isn't a problem with libCEC
