### ISSUE TITLE
TV device disappears

### ISSUE THREAD

**Issue by rayzorben** [Pulse-Eight/libcec#313]
Using cec-client on RPi. I turn on my TV, and do an `echo scan | cec-client -s -d 1` and get output showing my Samsung TV.

I can turn it off via `echo standby 0 | cec-client -s` and as well I can turn it on.

After using the remote control to turn off the TV (haven't tested with using cec-client) the TV continues to show up in standby mode.

After a while however, the TV disappears, and an `echo scan | cec-client -s -d 1` does not report the TV at all. At this point I am unable to turn the TV on.

**Comment by opdenkamp** [comment]
Please pastebin the output, without `-d 1` or nothing of interest will show up

**Comment by opdenkamp** [comment]
Closing this since there has been no response for 4 months
