### ISSUE TITLE
Does libcec supports Android?

### ISSUE THREAD

**Issue by usasaradhi** [Pulse-Eight/libcec#315]
Hi does it support Android platform. If yes, please guide me to build it for Android. Or if you have pre built binaries provide the link to download it. 
From Android version 5.0, they introduced TV Input framework. This framework has support for HDMI CEC. 
Can i use your lib cec for android(If available) on Android versions after 5.0?

**Comment by opdenkamp** [comment]
Linux in-kernel CEC is not supported yet. There's a ticket about it here: https://github.com/Pulse-Eight/libcec/issues/67
