### ISSUE TITLE
cec-client is not showing any connection on Wandboard B1

### ISSUE THREAD

**Issue by DestiGroup** [Pulse-Eight/libcec#318]
when I hit `cec-client -s`  the following thing will be appeared in terminal.

_opening a connection to the CEC Adapter...
DEBUG:        [    323]   unregistering all CEC clients
DEBUG:        [    325]   Broadcast (F): osd name set to 'Broadcast'
NOTICE:       [    328]   connection opened
DEBUG:        [    331]   process thread started
DEBUG:        [    331]   << Broadcast (F)  ->  TV  (0): POLL
TRAFFIC:     [    337]   <<f0_

And the TV that I'm using is SAMSUNG which is having ANYNET+. Its not finding my Wandboard in its cec connected lists. Other devices are shown when my wandboard is not connected. They are also not shown when wandboard is connected. Any problem with the wandboard. 

FYI: I've build the **Linux Kernel** enabling `MXC_HDMI_CEC=y` in config file and also put the `&hdmi_cec { status:'okay' }` in wandboard_dtsi.

Any kind of help is greatly appreciated

**Comment by opdenkamp** [comment]
I had never heard of a Wandboard before, so I had to Google it. The first thing that comes up is this: https://project-insanity.org/blog/2014/01/24/wandboard-with-hdmi-cec-and-xbmc/ which may help.

Also, try swapping HDMI cables.

Please contact the manufacturer if that doesn't work.
