### ISSUE TITLE
firmware upgrade EEPROM fail

### ISSUE THREAD

**Issue by gingerbeardman** [Pulse-Eight/libcec#332]
when upgrading my CEC adapter, firmware was updated to v7

but the EEPROM part failed

**Comment by 9000h** [comment]
where can I found a firmware v7 ß

**Comment by malard** [comment]
https://www.pulse-eight.com/p/104/usb-hdmi-cec-adapter#downloads

**Comment by 9000h** [comment]
thank's !

**Comment by gingerbeardman** [comment]
Eventually I managed to fully update my adapter (firmware and EEPROM) using a Windows XP Virtual Box.

**Comment by 9000h** [comment]
yes would be great if linux and macos updates where available

**Comment by gingerbeardman** [comment]
@9000h please add your voice at https://github.com/Pulse-Eight/libcec/issues/334
