### ISSUE TITLE
OSD string truncated

### ISSUE THREAD

**Issue by gingerbeardman** [Pulse-Eight/libcec#333]
using 2.1.1 for Mac OS X

```
device #4: Playback 1
address:       1.1.0.0
active source: yes
vendor:        Unknown
osd string:    NintendoSwitc
CEC version:   1.3a
power status:  on
language:      ???
```

on my TV via CEC it shows as NintendoSwitch, with the final character h

also: 
```
TRAFFIC: [            8183]	>> 4f:87:00:09:bf
DEBUG:   [            8183]	>> Playback 1 (4) -> Broadcast (F): device vendor id (87)
DEBUG:   [            8183]	Playback 1 (4): vendor = Unknown (0009bf)
```
0009bf is Nintendo

**Comment by pfiaux** [comment]
It might be a limitation on the OSD string length in libcec. If the OSD string is handled the same way as `strDeviceName` in `libcec_configuration` it looks like it's limited to a length of 13 characters.

For example in cecetypes.h:
`typedef char cec_osd_name[14]; /**< the name of the device */`
(I'm not sure but my guess is 13 + null termination)

**Comment by opdenkamp** [comment]
Just checked, it looks like this is a bug that has been corrected incorrectly last time... Maximum length is 14 bytes according to spec, not 13. Because other apps depend on the NULL terminator most likely, I can't change this without bumping the major version number.

**Comment by opdenkamp** [comment]
this will be fixed after the version bump
