### ISSUE TITLE
Updated non-Windows builds?

### ISSUE THREAD

**Issue by gingerbeardman** [Pulse-Eight/libcec#334]
I have tried to build the Mac version but it is beyond me as I do not know how to setup p8-platform

Could you please release updated non-Windows builds?

Thanks!

**Comment by gingerbeardman** [comment]
I see v4.0.2 has just been released for Windows

Linux is all but abandoned.
Mac seems to be also.

Please help us non-Windows users.

**Comment by malard** [comment]
Not really?, Mac we don't have the ability to compile. But Linux has packages within the various distros package managers, so we don't publish a download on our website https://packages.debian.org/source/sid/libcec

**Comment by gingerbeardman** [comment]
Sorry I was specifically taking about the firmware upgrader.

If you give me help I'll be happy to compile the Mac version for you.

**Comment by jordanade** [comment]
Yeah, where is cec-firmware-upgrade? Can anyone help?

**Comment by gingerbeardman** [comment]
I ended up using VirtualBox running Windows just to upgrade my firmware.

**Comment by opdenkamp** [comment]
Unfortunately we can't support firmware updates on non-Windows at the moment, but you shouldn't have to update the firmware unless you have a very old device.
