### ISSUE TITLE
Firmware v7 reports that v4 has been installed

### ISSUE THREAD

**Issue by gingerbeardman** [Pulse-Eight/libcec#335]
Firmware upgrader reports that V4 has been installed after successful install.

Checking adapter V7 has actually been flashed.

Windows updater

![screen shot 2017-04-07 at 10 44 31](https://cloud.githubusercontent.com/assets/49612/24794914/57ce94ee-1b7f-11e7-8eac-b8592e104fce.png)

**Comment by opdenkamp** [comment]
This is a bug in the firmware upgrade tool, which contains a wrong label. It did actually flash the correct version of the firmware. You can verify this with "cec-client.exe -l"

**Comment by gingerbeardman** [comment]
@opdenkamp that's what I meant by my second sentence

if I should report this elsewhere please let me know where exactly.

**Comment by opdenkamp** [comment]
This has been fixed in more recent versions, but I forgot to close this ticket. Thanks
