### ISSUE TITLE
Unable to run cec-client.exe on Windows XP (32-bit)

### ISSUE THREAD

**Issue by gingerbeardman** [Pulse-Eight/libcec#337]
Do I need to use XP 64-bit or am I missing something?

![screen shot 2017-04-07 at 10 43 42](https://cloud.githubusercontent.com/assets/49612/24795001/b5748216-1b7f-11e7-8604-f5ff23a48f46.png)

**Comment by opdenkamp** [comment]
Unfortunately XP is no longer supported by Microsoft's current toolchain. Only Vista+ is still supported.
Only older versions of libCEC, which don't use the latest toolchain, will work on XP.

**Comment by gingerbeardman** [comment]
@opdenkamp thanks I'll upgrade my VM
