### ISSUE TITLE
How to show all CEC log in cec-client

### ISSUE THREAD

**Issue by cozypi** [Pulse-Eight/libcec#339]
I install libcec in my raspberry pi3 and can use cec-client to see CEC log.
But this CEC log looks like not all CEC log, just related with "Recorder" and "broadcast".
I would like to show all CEC log which includes no relation with "Recorder" such as "Player" -> "TV" for full debug use.

How to show all CEC log in cec-client?

Thanks

**Comment by opdenkamp** [comment]
cec-client is a debugging and testing client for libCEC primarily. If you don't provide any command line options, then it'll show all CEC traffic (and more)
