### ISSUE TITLE
CEC version 2.0

### ISSUE THREAD

**Issue by xemnaskami** [Pulse-Eight/libcec#340]
I want to know if LibCEC is able to detect devices which are in CEC 2.0, and saying it in the scan option.

Actually it's looks like if there is nothing after the 1.4 version, so I don't know how verifying the CEC version of my new devices.

**Comment by opdenkamp** [comment]
yes, libCEC is able to detect 2.0 devices, which are fully backwards compatible with earlier CEC versions (or they should be according to the spec). run cec-client and type "scan" to see which versions devices are reporting.
