### ISSUE TITLE
Panasonic TV not switching back to RPi as active source anymore

### ISSUE THREAD

**Issue by Forage** [Pulse-Eight/libcec#343]
Hi,

My TV would normally switch back to Kodi as source when turning off my TV (power or standby), followed by turning it on again before the issue was introduced. Now this doesn't happen anymore, forcing my to switch manually every time. Since Kodi is my primary viewing channel, this basically comes down to every time I use the TV.
The slightly odd thing is that entering the AV selection menu on the TV is already enough to make it switch source. The HDMI channel for Kodi will already be selected, so either pressing the back button or the OK button will do the trick, just to make the menu go away.

I've narrowed it down to [build #0315 of LibreELEC](http://forum.kodi.tv/showthread.php?tid=298461&pid=2549210#pid2549210) being the first which has the issue, which just so happens to have [libcec changes](https://github.com/Pulse-Eight/libcec/compare/0a97062dd4b196c...8563411d1b449ed) as well. 

Together [with me](http://forum.kodi.tv/showthread.php?tid=298461&pid=2573854#pid2573854) are [others as well](http://forum.kodi.tv/showthread.php?tid=298461&pid=2566522#pid2566522) having the same problem and providing more details.

Let me know if you need any more information to track the issue down in order to fix it.

**Comment by VimesUK** [comment]
Yup, still there as a problem and referenced here....

http://forum.kodi.tv/showthread.php?tid=298461&pid=2590588#pid2590588

The changes made in build 315 stopped my Panasonic TV from "source from switching to this device on startup".
It just starts the TV up in TV mode and will no longer switch to the HDMI input of the Pi3.

See post noted for detail
