### ISSUE TITLE
Linux installer 404

### ISSUE THREAD

**Issue by positlabs** [Pulse-Eight/libcec#349]
This url is a 404: https://packages.debian.org/sid/libcec3

Found on http://libcec.pulse-eight.com/Downloads

<img width="295" alt="screen shot 2017-05-12 at 8 49 13 pm" src="https://cloud.githubusercontent.com/assets/1918844/26022238/8ef86f08-3754-11e7-9319-13b6d87bb46e.png">

**Comment by opdenkamp** [comment]
Yeah those links won't work for Linux in general. Please check your Linux distribution for instructions on how to install libCEC. If you're using Debian/Ubuntu: `sudo apt-get install cec-utils`

@malard can you remove the link for Linux please

**Comment by malard** [comment]
@opdenkamp  is it safe to just say "sudo apt-get install cec-utils" on the download page instead?

**Comment by opdenkamp** [comment]
For Debian based systems, yes. `yum install libcec` for RedHat based ones iic. For others, people will have to check themselves because there is no generic way on Linux
