### ISSUE TITLE
no CEC standby when Kodi is playing music

### ISSUE THREAD

**Issue by OndrejSindler** [Pulse-Eight/libcec#350]
Hello,
I use RPi2 with Philips TV and I have problems with sending TV to standby when playing (or when paused) music.

_When no music is playing then everythink is OK:_
19:30:50.139` T:1962746784   DEBUG: CAnnouncementManager - Announcement: OnScreensaverActivated from xbmc
19:30:50.139 T:1962746784   DEBUG: GOT ANNOUNCEMENT, type: 4, from xbmc, message OnScreensaverActivated
19:30:50.140 T:1805644704   DEBUG: CecLogMessage - << requesting vendor ID of 'TV' (0)
19:30:50.140 T:1805644704   DEBUG: CecLogMessage - 'give device vendor id' is marked as unsupported feature for device 'TV'
19:30:50.140 T:1805644704   DEBUG: CecLogMessage - << putting 'TV' (0) in standby mode
19:30:50.141 T:1805644704   DEBUG: CecLogMessage - << 10:36
19:30:50.142 T:1962749952   DEBUG: ------ Window Init () ------

_When music is playing or is paused, then screensaver is switched on but it isn't followed by CEC request (at least it is not visible in log file):_
19:36:36.719 T:1962746784   DEBUG: CAnnouncementManager - Announcement: OnScreensaverActivated from xbmc
19:36:36.719 T:1962746784   DEBUG: GOT ANNOUNCEMENT, type: 4, from xbmc, message OnScreensaverActivated
19:36:36.722 T:1962749952   DEBUG: ------ Window Init () ------

When I switch TV to standby manually by remote... it is then correctly waked up by CEC when screensaver is deactivated.
I used to use monitor for the same purpose and it was put into standby regularly without any problem.
I'm using libCEC v4.0.1 in Kodi 17.1 (Git:fc1619b).
Thank you.

**Comment by opdenkamp** [comment]
This is a problem on Kodi's side and not in libCEC. Please create a ticket on http://trac.kodi.tv/
