### ISSUE TITLE
LibCEC 4.0.2 - Windows installer

### ISSUE THREAD

**Issue by Shamshala** [Pulse-Eight/libcec#353]
Hi,

after i updated the LibCEC to v4.0.2(installer from pulse-eight website) i get an error "HRESULT: 0x8007007e" and then app crash everytime i try to launch it. If i've checked this problem on the internet properly, it has something to do with compilation process. Could you please fix that?

OS is Windows 7 x64

Thanks

**Comment by yoGhurrt1** [comment]
Same here - Win 10 x64 Creators Update. I tried to reinstall everything few times, reinstalled some drivers (because it also had issue after update to CU), including installing LibCEC in location with lower security permissions like main folder on C: ,but nothing changed.

**Comment by traufeisen** [comment]
Same here on Win 10 x64 Creators Update

**Comment by Shamshala** [comment]
Ok, here it looks like deadvillage... Guys, install the **Microsoft Visual C++ 2015 Redistributable** (x86 and x64 to be sure), then new libCEC.

**Comment by malard** [comment]
we're busy launching a new product so we havent had time to focus on open libCEC tickets. 

I assure you they will be looked into soon
