### ISSUE TITLE
Firmware upgrade under Linux

### ISSUE THREAD

**Issue by Anonym-tsk** [Pulse-Eight/libcec#359]
How to upgrade firmware of USB-cec?
cec-firmware-upgrade no longer supported and was removed from ppa.

**Comment by opdenkamp** [comment]
You'll have to use Windows to upgrade the firmware. We can't support Linux firmware upgrades at the moment.

**Comment by Anonym-tsk** [comment]
Maybe there is some way? Manually flash the new version using the old cec-firmware-upgrade?

**Comment by opdenkamp** [comment]
Which device do you have and which firmware version is it running now?

**Comment by Anonym-tsk** [comment]
https://www.pulse-eight.com/p/104/usb-hdmi-cec-adapter
Firmware v4

**Comment by opdenkamp** [comment]
That firmware version should be fine then for this device. Any reason why you want to upgrade the firmware?

**Comment by Anonym-tsk** [comment]
No reason, just new version. Do you have changelog?

**Comment by opdenkamp** [comment]
No, there's no changelog available unfortunately. Unless you're having trouble, you shouldn't have to upgrade the firmware.
