### ISSUE TITLE
Windows system tray icon unfavorable

### ISSUE THREAD

**Issue by ThomDietrich** [Pulse-Eight/libcec#368]
As can be seen below you should consider a redesign of the tray icon...

![grafik](https://user-images.githubusercontent.com/2870104/28896768-1bb0a982-77de-11e7-9c22-80f3086c8af3.png)

**Comment by opdenkamp** [comment]
the icon has been replaced in the latest 6.0 release

**Comment by ThomDietrich** [comment]
Thanks!
