### ISSUE TITLE
LG simplink not working with libcec

### ISSUE THREAD

**Issue by dcolens** [Pulse-Eight/libcec#37]
It is not possible to use the Simplink menu or changing source to get the remote connected to xbmc with the latest openelec. 
CEC debug log of the latest beta openelec 4.1.6 is at http://pastebin.com/PfJ62H0c.

**Comment by NemoN** [comment]
Any news here? I have the same problem. Currently the pulse eight adapter is without usage for me.

**Comment by opdenkamp** [comment]
just tested with the upcoming libCEC 2.3.0 and it's working correctly now

**Comment by dcolens** [comment]
cool am eager to test it :)

Did

**Comment by dcolens** [comment]
This issue is still present in 3.0.0, same behaviour as before : It is not possible to use the Simplink menu or changing source to get the remote connected to xbmc with the latest openelec.

**Comment by opdenkamp** [comment]
I've tested this on my own Simplink TV. Is the adapter set up correctly in system -> input devices -> peripherals -> CEC adapter? Please check, and submit a new debug log if it's all ok.

**Comment by opdenkamp** [comment]
@dcolens can you try again with 3.0.1 please once it's been picked up by your distribution and submit a new debug log if it doesn't work.

will close this report if I haven't heard back next week.

**Comment by dcolens** [comment]
FYI as 3.0.1 is not avail yet in openelec, I launched the cec-client without pressing any key on TV or AVR => http://pastebin.com/9pw4w2uW (shows some unknown command, also ran a scan at the end).

I also enabled debugging on kodi and here is a capture when it fails, actions done: press simplink and select the HDD device (=openelec), result: almost immediate failure message on screen => http://pastebin.com/U3u7wzuP

(PS: I get the same if I remove AVR and chromecast)

**Comment by dvcsender** [comment]
I have an LG TV and have installed libcec on my pi b+ by updating it to jessie. It installed fine and recognises the tv and what is currently active, but it won't do anything. It won't power on, power off etc. It accepts the commands and sends traffic, but it just doesn't work. Is this still an issue? FYI Simplink is turned on.

**Comment by dvcsender** [comment]
You can probably ignore the above. I tried it on a Samsung TV and same result. I'll try a fresh install.

**Comment by dvcsender** [comment]
I've installed libcec successfully on my raspberry with jessie. LG is working, but only to switch the tv on. Can't put into standby or switch sources. 

Any ideas?

**Comment by dcolens** [comment]
Still the same behaviour with 3.0.1, here's a paste after a power cycle of the TV and trying to use simplink to connect to kodi (openelec): http://pastebin.com/kF4BAvJa

**Comment by dcolens** [comment]
I upgraded the TV to firmware 3.75 (it ran a lower version before), this in combination with libcec 3.0.1 seems to resolve the issue, will test a bit more and update this issue with the results.
Thanks for your support.

**Comment by dcolens** [comment]
after a cold reboot of the TV, no way to connect to libcec anymore. Still testing

**Comment by dcolens** [comment]
that last one was a bad cable, it still works with 3.0.1. Closing this issue. Thanks for making libcec :)

**Comment by cuenotje** [comment]
Hello,
i have the same problem with an LG TV LW659S an rasberry pi2 with OSMC.
This lib is compatible with raspberry Pi2 ?
Thx
