### ISSUE TITLE
Samsung Series 9 only basic on/off works

### ISSUE THREAD

**Issue by timdonovanuk** [Pulse-Eight/libcec#370]
The basics, such as:

_echo "on 0" | cec-client -s
echo "tx 10:36" | cec-client -s (turn tv off)
echo "tx 10:91" | cec-client -s (get language)_

these all work but....thats about it. Any other commands, even using direct ones don't seem to do anything. For example:

_echo mute | cec-client -d 4_ 

returns mute: 7F and nothing happens. Using more custom commands e.g. switch source _echo _"tx 10:82:00:00" | cec-client -d 4_ simply returns

_log level set to 4
No device type given. Using 'recording device'
CEC Parser created - libCEC version 4.0.2
no serial port given. trying autodetect:
 path:     Raspberry Pi
 com port: RPI_

_opening a connection to the CEC adapter...
NOTICE:  [             113]     connection opened
NOTICE:  [             370]     registering new CEC client - v4.0.2
NOTICE:  [            1069]     CEC client registered: libCEC version = 4.0.2, client version = 4.0.2, firmware version = 1, logical address(es) = Recorder 1 (1) , physical address: 3.0.0.0, git revision: libcec-4.0.2+8-8563411~dirty, compiled on Sun Apr  2 17:04:01 UTC 2017 by root@hostname: Name or service not known on Linux 4.4.0-57-generic (armv7l), features: P8_USB, DRM, P8_detect, randr, RPi_

This output is pretty much all I get whenever I try any custom commands. So I'm very much limited to on/off...here is some debug info:

cec-client -i
libCEC version: 4.0.2, git revision: libcec-4.0.2+8-8563411~dirty, compiled on Sun Apr  2 17:04:01 UTC 2017 by root@hostname: Name or service not known on Linux 4.4.0-57-generic (armv7l), features: P8_USB, DRM, P8_detect, randr, RPi

echo scan | cec-client -s -d 1
opening a connection to the CEC adapter...
requesting CEC bus information ...
CEC bus information
===================
device #0: TV
address:       0.0.0.0
active source: yes
vendor:        Samsung
osd string:    TV
CEC version:   1.4
power status:  on
language:      eng

device #1: Recorder 1
address:       3.0.0.0
active source: no
vendor:        Pulse Eight
osd string:    CECTester
CEC version:   1.4
power status:  on
language:      eng

device #4: Playback 1
address:       1.1.0.0
active source: no
vendor:        Sony
osd string:    PlayStation 4
CEC version:   1.3a
power status:  standby
language:      ???

device #8: Playback 2
address:       2.0.0.0
active source: no
vendor:        Google
osd string:    Chromecast
CEC version:   1.4
power status:  on
language:      ???

currently active source: TV (0)

Thank you for any assistance.

**Comment by opdenkamp** [comment]
Volume control is not supported by most TVs and only supported when using a CEC compatible AVR.
Because you passed "-d 4", all responses from the TV are filtered out of the output, but the command is probably rejected (opcode feature abort) or ignored by the TV.

Also, "on 0" just powers on the TV, but does not make the Pi active source. The "as" command does. When a source is not active, then the TV may ignore commands such as volume control from the source too.
