### ISSUE TITLE
Compiling on Raspberry Pi 3 with OSMC

### ISSUE THREAD

**Issue by mattie47** [Pulse-Eight/libcec#373]
Hi,

Following https://github.com/Pulse-Eight/libcec/blob/master/docs/README.raspberrypi.md I thought it was worth adding what I had to do to get the latest version to build.

I'm running OSMC and and did not have the folder /opt/vc/include

I then saw somewhere to try install libraspberrypi-dev, however I could not find this package. 

So the answer in my case I found in https://discourse.osmc.tv/t/howto-install-a-vnc-server-on-the-raspberry-pi/1517/2 which is to:

_`sudo apt-get install rbp-userland-dev-osmc` for the development headers. These will match the userland libraries that we ship in OSMC_

I don't know if build-essential was required, but I also did:

`osmc@osmc:~/libcec/build$ sudo apt-get install build-essential`

At this point, I then got the following issue:

```
Make Error at src/libcec/cmake/CheckPlatformSupport.cmake:193 (if):
  if given arguments:

    "3" "GREATER" "2" "AND" "3" "GREATER_EQUAL" "7"

  Unknown arguments specified
Call Stack (most recent call first):
  src/libcec/CMakeLists.txt:133 (include)


-- Configuring incomplete, errors occurred!
See also "/home/osmc/libcec/build/CMakeFiles/CMakeOutput.log".
See also "/home/osmc/libcec/build/CMakeFiles/CMakeError.log".
osmc@osmc:~/libcec/build$
```

The following post explains how to fix this: https://github.com/Pulse-Eight/libcec/issues/362#issuecomment-317258888

Thanks,

Matt

**Comment by opdenkamp** [comment]
https://github.com/Pulse-Eight/libcec/issues/362 is still open indeed. Closing this one as duplicate. The issue affects all platforms, and hasn't been included in any release yet.
