### ISSUE TITLE
cec-client failing on Raspbian stretch

### ISSUE THREAD

**Issue by dbghb** [Pulse-Eight/libcec#377]
After updating to stretch (on a Pi 3) cec-client fails with
"cec-client: symbol lookup error: /usr/lib/arm-linux-gnueabihf/Utils6FormatEPKczlibcec.so.4: undefined symbol: _ZN11StringUtils6FormatEPKcz"

This seems to be a recurring bug. 

I also compiled from source but the same problem shows up.

**Comment by retikulumx** [comment]
Same for me. Looks like the same issue as in [#149](https://github.com/Pulse-Eight/libcec/issues/149)

**Comment by retikulumx** [comment]
Ok, the issue is solved in current update (Debian Stretch Repository). Just update & upgrade

**Comment by dbghb** [comment]
Verified.

**Comment by fcanepa** [comment]
I'm currently running uptodated Debian Stretch on my rpi2, and I've the same error. How to fix rpi2 ?

**Comment by retikulumx** [comment]
Just update libcec

**Comment by fcanepa** [comment]
Ok, my apt.source.d was wrong... Now libcec is update to 4.0.2.3~stretch and it works!
