### ISSUE TITLE
Turn on pc after shutdown (Win10)

### ISSUE THREAD

**Issue by NoFixIT** [Pulse-Eight/libcec#378]
When using pulse eight USB adapter on my HTPC running libreelec I'm able to turn on the HTPC by selecting the source on my TV. However as soon as I load up windows 10 and shut down selecting the source does not turn on the HTPC.

**Comment by opdenkamp** [comment]
You'll have to run an application that uses libCEC (like Kodi) to make this work, and it has to be configured to use the correct HDMI input of the TV when using Windows. This is done automatically when using Libreelec/Openelec.
