### ISSUE TITLE
Kodi Wake up from Sony tv doesn't work 

### ISSUE THREAD

**Issue by Sph1re** [Pulse-Eight/libcec#386]
It is a revival of a old issue [https://github.com/Pulse-Eight/libcec/issues/309](url)

Hello,

Since the update of libcec (4.0.x), it's impossible to wake up kodi by turning on the tv.
The screen is black (the standby of the display by kodi) I am obliged to press several times on the keys of the remote control to see kodi. The same thing for the screensaver
It seems a little innocuous, but if the tv is started during the screensaver, it will remain on indefinitely.(I do not have the sleep function if no signal)

My system:

- PC or RPI 3 (libreelec 8.0.2)
- PulseEight (pc only)
- Kodi V17 (Krypton)
- Windows 10
- Sony TV KDL 40EX711

**Comment by opdenkamp** [comment]
I can't reproduce this with libCEC 4.0.2 and current Kodi master. If this still happens for you, then I'll need a new log from Kodi, with libCEC debugging enabled.
