### ISSUE TITLE
Using multiple logical devices?

### ISSUE THREAD

**Issue by samgurtman** [Pulse-Eight/libcec#388]
Perhaps I misunderstand how CEC is supposed to operate, but I'm under the impression that you can run multiple "devices" on a single HDMI port. My specific use case is having an "audio system" device run at the same time as Kodi's "recorder" device. The TV will send volume commands to the RPI which will then send IR blasts in response. 

I can't seem to get this to operate with cec-client or libcec. Adding a "audio system" device seems to hijack the existing cec connection rather than creating a new connection.

Is this possible or am I misunderstanding something?

**Comment by opdenkamp** [comment]
You can do it with cec-client, but it'll have to be started by a single instance: `cec-client -t p -t a` will allocate both a player and avr.
