### ISSUE TITLE
CECAudioSystem doesn't seem very useful

### ISSUE THREAD

**Issue by asquared** [Pulse-Eight/libcec#407]
I'd like to use libcec to act as an audio system - that is, I want to write code that handles incoming volume up, volume down, and give audio status commands. It looks like most of this is already implemented in [CECAudioSystem.cpp](https://github.com/Pulse-Eight/libcec/blob/libcec-4.0.2/src/libcec/CECClient.cpp) but I cannot find any way to access this object via the public API. That is, it always returns an audio status of "unknown" to the TV, and I've found no way to change this. There is the SetAudioStatus() method but there is no apparent means to access this via ICECAdapter. Is this intentional? What is the purpose of this class if the volume it returns cannot be changed?

**Comment by opdenkamp** [comment]
Audio control has not been implemented fully in this version of libCEC indeed. A commercial version of the library is available that does provide features like this. Please contact support@pulse-eight.com if you're interested.
