### ISSUE TITLE
How to uninstall Raspberry version?

### ISSUE THREAD

**Issue by eporedieis** [Pulse-Eight/libcec#408]
Hello, I installed the Raspberry version following the "readme" instructions and now I have a lot of problems on my OS. How could I uninstall?
Thank you

**Comment by opdenkamp** [comment]
you'd have to remove the files from the /usr/local directory to remove it. if you're not a developer, then you best just install libcec from your distribution instead of building it from source (presumably apt-get install libcec cec-utils)
