### ISSUE TITLE
Tuner Controls

### ISSUE THREAD

**Issue by kdschlosser** [Pulse-Eight/libcec#411]
One of the things I have noticed is that the library has no convenience methods/functions for handling Tuner controls. I am writing a python library with libcec as the entry point to the CEC device. This is one of the last things I would like to add. Now I know I am able to send raw commands which i do not have a problem doing. But my issue is trying to figure out the correlation between the hex segments. it is not simply split apart like the rest of the CEC command structure. I have been unable to locate some kind of an whitepaper on the CEC command structure that explains this part of the control codes. Not sure as to why this information is so secretive. If someone could point me in the direction to the whitepaper on this. or if they want to type out what I am sure would be a book on how it is set up that would work as well. Anything that can help me out would be appreciated.

Thanks again
Kevin

**Comment by opdenkamp** [comment]
Sorry for the late response, but we've never implemented anything like this because none of the devices that we've seen support these opcodes. It's legacy stuff that's in the protocol still for backwards compatibility reasons.
