### ISSUE TITLE
[RFC] Add support for CEC 2.0 standards as introduced in HDMI 2.0?

### ISSUE THREAD

**Issue by Hedda** [Pulse-Eight/libcec#42]
This is really only a RFC (Request for Comments) suggestion/request regarding HDMI 2.0 and CEC 2.0 compatibility:

Each version of HDMI have introduced new CEC features, and HDMI 2.0 is no different.

CEC for HDMI 2.0, now referred to as "CEC 2.0" is said to been a re-worked / re-tooled standard.

CEC 2.0 add support for new standard CEC operational codes introduced in HDMI 2.0 and as of HDMI 2.0, CEC 2.0 have to be implemented and support CEC extensions like remote control pass-through, system audio control and standby have to be implemented as part of CEC as well.

Which new codes, standards, buttons, features from CEC 2.0 are planned for LibCEC?

http://www.trustedreviews.com/opinions/hdmi-2-0-vs-1-4

When will you be able to say that LibCEC is HDMI 2.0 and CEC 2.0 compatible?

Indirectly this question also goes on to ask if Pulse-Eight CEC Adapters will be HDMI 2.0 and CEC 2.0 compatible?

There was quite a long time ago now that we heard any announcements from Pulse-Eight about their CEC adapters or other.

CEC 2.0 main goal is however unified remote control functionality, one CEC standard.

http://www.hdmi.org/manufacturer/hdmi_2_0/hdmi_2_0_faq.aspx

"CEC extensions provide more expanded command and control of consumer electronics devices through a single control point".

HDMI 2.0 adds support for "CEC 2.0" and I'm now wondering what it means for LibCEC?

http://chipdesignmag.com/display.php?articleId=5318

"Consumers find it very frustrating that electronics manufacturers haven’t worked together to standardize the remote control. Each consumer electronics manufacturer has its own proprietary Bluetooth link for its remote control system that includes various optional features and will not interoperate with equipment designed by other manufacturers. The universal remote controls that are available on the market today tend to be difficult to use, require awkward setup routines and sometimes only have the ability to control a subset of equipment features. The result is that most homes have multiple remotes to operate their DVDs, TVs and set-top boxes. As an alternative to proprietary remote technology, HDMI 2.0 has upgraded the Consumer Electronics Control (CEC) functionality to version 2.0, which defines a set of operational codes to enable true universal remote controls. Once instantiated, CEC 2.0 lets consumers control up to 15 CEC-enabled devices, each connected through HDMI, by using only one of their remote controls (for example, controlling a television set, set-top box, and DVD player using only the remote control of the TV). CEC 2.0 enables greater integration and interoperability between HDMI devices of different brands, greatly enhancing the user experience and enabling seamless operation between devices. 

https://gigaom.com/2013/09/05/hdmi-2-explained/

" One of the cool things about HDMI has been CEC, the control capability that amongst other things makes it possible for a Chromecast device to turn on a TV. However, the implementation of many CEC features was voluntary for consumer electronics manufacturers. With HDMI 2.0, this changes, and things like remote control pass-through, system audio control and standby have to be implemented as part of CEC as well. In other words: You’re going to need fewer remote controls to get more stuff done."

**Comment by sm-Fifteen** [comment]
> As the person who drafted most of the CEC 2.0 spec (I am the technical chair for CEC & HDMI Control) I would love to have it included. However the specification isn't public so it isn't currently in our public offering until we can come up with a way to include it without breaching any confidentiality agreements.
> 
> That said, the real issue is documentation, I'm sure we will do it, but you will just have to figure out for yourself how to use them :)

@malard: Is this ever going to be sorted out? It's been a decade by now, and lack of CEC 2.0 support still prevents users of libCEC from using/understanding things like Feature support reporting, Dynamic Lipsync, use of addresses 12 and 13 as Backup roles and all the other tidbits (and general spec tightening) that CEC 2.0 added.

The [Linux Kernel CEC subsystem](https://www.kernel.org/doc/html/latest/driver-api/media/cec-core.html) has complete support for CEC 2.0 and seemingly has had since 2016, yet I'm not aware of any breach of confidentiality having been brought up against them in the meantime. AMD [recently got denied support for HDMI 2.1](https://www.phoronix.com/news/HDMI-2.1-OSS-Rejected) features in its open-source Linux driver, but it's still allowed to have complete support for HDMI 2.0. I'm not sure how libCEC would be legally prevented from implementing CEC 2.0 given these precedents.

**Comment by malard** [comment]
Honest answer at this point is that we have not done it, however with respect to your questions, we can't publish the spec, so we can implement it, but in theory explaining what it does may be tricky, however I think in reality the risk to us now is very low and so I will see when we can make it happen

Thanks
