### ISSUE TITLE
what are volup/voldown hex codes?

### ISSUE THREAD

**Issue by untitledlt** [Pulse-Eight/libcec#421]
I can increase/decrease volume with `echo "volup" | cec-client RPI -s -d 1` but i can not find `volup`/`voldown` values in hex.
Also I can not find volume codes on cec-o-matic. 
Where can I find hex values for those built-in cec-client commands?

**Comment by fholzer** [comment]
https://github.com/Pulse-Eight/libcec/blob/ab6c13846af6d56f26a1632fcde070e9b9c481b4/include/cectypes.h#L655

**Comment by opdenkamp** [comment]
thanks @fholzer :)
