### ISSUE TITLE
cec-client on Windows 10 --> TV turns on automatically after some minutes

### ISSUE THREAD

**Issue by TuxFloHB** [Pulse-Eight/libcec#424]
Hi, 

we are using the USB-CEC Adapter with Windows 10 and a Samsung MU6179 TV. 
Powering on and off the TV is working fine. 
But when the TV is powered off, after 10 - 30 minutes it always turns on again automatically!

The TV has already been replaced, because we thought that this was a hardware issue. But nothing changed. When I remove the cec adapter, the TV remains off.

Do you have any idea for these behaviour? 

regards
Florian

**Comment by PeterW123** [comment]
We have exactly same issue with Windows 10 and Samsung MU6300 TV, the TV always turns on automatically by USB-CEC Adapter.  Just waiting for solution.

**Comment by aanderse** [comment]
I have a Samsung UN50MU6070F which turns on randomly 2-5 times a day if my pulse 8 cec adapter is plugged in. This happens regardless of operating system (tested on Windows 10 and several Linux variants).

If there is any actions I could take, any logs I could produce to help resolve this issue please let me know.

**Comment by opdenkamp** [comment]
it needs a new firmware which has been tested today and will be available later this week

**Comment by opdenkamp** [comment]
you can download the firmware upgrade tool here: [cec-firmware-v9.zip](https://github.com/Pulse-Eight/libcec/files/2557238/cec-firmware-v9.zip)
it will be uploaded to our website

**Comment by aanderse** [comment]
Great thanks! Will try out tonight.

**Comment by TuxFloHB** [comment]
When will the new driver for Windows be available?

**Comment by aanderse** [comment]
@opdenkamp recompiled libcec against d57d3ac91a2e6c7f224082fc749331210718a08b and then built kodi this morning... and unfortunately tv just turned on 20 minutes ago. Note that I have applied the firmware update you provided above.

After updating libcec and kodi I rebooted the pc, put the computer to sleep, and then the tv was off. Can you give me the steps you took to reproduce successfully keeping the tv off? Is there any logging information I can produce that might give us a clue?

**Comment by aanderse** [comment]
@opdenkamp Whenever I enable cec logging in component debugging the setting will not persist across reboots or even restarting Kodi.

Attached is my kodi.log file.
[kodi.log](https://github.com/Pulse-Eight/libcec/files/2579326/kodi.log)

**Comment by TuxFloHB** [comment]
@opdenkamp Where can I download the new driver for Windows to fix the issue with our Samsung TV?

**Comment by aanderse** [comment]
@opdenkamp I've left my computer on for the last ~24 hours with the TV turned off and the TV has not turned on. So it appears that as long as the computer is turned on your fixes are working as expected, though if the computer is turned off or in sleep mode this doesn't work.

What is the expectation?
