### ISSUE TITLE
Signal handling in cec-client.cc seems incorrect

### ISSUE THREAD

**Issue by akabel** [Pulse-Eight/libcec#425]
The signal handler touches a global variable of type int (whise value is used as the stopping condition for the main loop). This has to be a volatile sig_atomic_t, otherwise, the compiler is free to assume the value never changes. That's what happens on the current Debian pkg for retropie  -- cec-client processes are unkillable.

**Comment by opdenkamp** [comment]
sounds like a compiler optimisation bug?

https://port70.net/~nsz/c/c11/n1570.html#5.1.2.3p5
> When the processing of the abstract machine is interrupted by receipt of a signal, the values of objects that are neither lock-free atomic objects nor of type volatile sig_atomic_t are unspecified, as is the state of the floating-point environment.

https://www.gnu.org/software/libc/manual/html_node/Atomic-Types.html
> In practice, you can assume that int is atomic

We can change it to `sig_atomic_t`, but it shouldn't be needed for ints according to the docs
