### ISSUE TITLE
Wrong HDMI input is activated during resume from standby.

### ISSUE THREAD

**Issue by darzur** [Pulse-Eight/libcec#43]
Hello,

After update to libcec 2.0.0 my Panasonic plasma doesn't properly wake anymore. I'm using Raspberry Pi with OpenELEC (Milhouse KODI builds). There are following scenarios:

1. TV in standby; RPi switched off

When I start RPi it properly boots up but at the end it doesn't switch my TV to the right HDMI input. It switches to the other HDMI and I have to manually select right HDMI using TV remote. As a side effect TV resolution defaults to 720p/50Hz and I can't change it in OpenELEC. It looks like it didn't recognized all available resolutions. Below you can find debug log for this scenario.

http://pastebin.com/8Zpupg8f

2. TV active and set to right HDMI input; RPi switched off

RPi boots up properly and everything seems to be fine at this stage. I can set all available resolutions and refresh rates and choose my default 1080p/23.98. Problems arise when I want to put RPi in sleep mode. It sleeps properly and TV switches to standby too but TV it's not able to properly resume.  RPi wakes TV but selects wrong HDMI input so I always have to select right HDMI from TV remote. Then everything works fine till next sleep when I have to repeat this procedure. Below debug log from this scenario.

http://pastebin.com/VRY3GHC2

I never had such problems with old LibCEC.
P.S. Tried to physically connect RPi to the other HDMI input but it didn't helped at all.

**Comment by opdenkamp** [comment]
the log is gone now, but the only reason for this combination to happen ('missing' resolutions and wrong hdmi input selected) would be an issue reading the EDID from the TV. this is not a problem in libCEC, but either some firmware problem in the Pi or an issue with the TV.

closing this ticket.
