### ISSUE TITLE
USB Adapter autodetection broken on MacOS Mojave

### ISSUE THREAD

**Issue by mikrohard** [Pulse-Eight/libcec#432]
I updated my Mac Mini today and noticed that Couch Slouch did not find my Pulse Eight USB adapter anymore. Same problem with command line cec-client (it didn't detect any devices).

I was able to fix the issue by replacing this line:
https://github.com/Pulse-Eight/libcec/blob/8adc786bac9234fc298c941dd442c3af3155a522/src/libcec/adapter/Pulse-Eight/USBCECAdapterDetection.cpp#L273

With this line:
`CFDictionarySetValue(classesToMatch, CFSTR(kIOSerialBSDTypeKey), CFSTR(kIOSerialBSDRS232Type));`

**Comment by WillDoy** [comment]
Will a new couch slouch build be available for download? I am non technical and was wondering if you could provide me with some guidance to implement the above. Any assistance much appreciated!
