### ISSUE TITLE
How to compile libcec for android?

### ISSUE THREAD

**Issue by rohit5ram** [Pulse-Eight/libcec#438]
I have tried as mentioned in the below link but couldn't succeed. Can you please guide me with a process on how can I generate the .so file and corresponding JNI files that I can use on android?

http://0x1c3.blogspot.in/2015/09/libcec-compilation-for-android-example.html

**Comment by opdenkamp** [comment]
Sorry, but we can only provide support for integrations to customers with a commercial license. Please contact support@pulse-eight.com if you're interested in a commercial license.

These instructions that you linked seem ok, though they might need some changes when using a more recent Android API/NDK.
