### ISSUE TITLE
Enquiring about plans to merge 4.0.3 to release branch

### ISSUE THREAD

**Issue by mseeley** [Pulse-Eight/libcec#442]
👋 Hi @opdenkamp thanks a lot for your continued effort.

I wanted to ask about your plans to merge 4.0.3 to the [`release`](https://github.com/Pulse-Eight/libcec/tree/release) branch. Before asking I wasn't able to find any context about possibly deferring the merge as part of a staggered release. I hope you don't mind my asking. 👼 

Many thanks!

**Comment by mseeley** [comment]
Hi @opdenkamp just one more kind bump to ask about `release` branch merge plans. We can work around on our own if you're otherwise unavailable.

Best regards, @mseeley. :)

**Comment by opdenkamp** [comment]
Sorry, completely forgot to do this. I'll merge this and the fix that got added after 4.0.3 next week.

**Comment by mseeley** [comment]
Hi @opdenkamp no worries + thanks a lot!
