### ISSUE TITLE
Python on Windows

### ISSUE THREAD

**Issue by takuy** [Pulse-Eight/libcec#446]
I am trying to use the Python hooks on Windows 10. I've dropped the _cec.pyd and _init_.py from the Windows distribution into: C:\Program Files\Python36\Lib\site-packages\cec

However, when I import cec, there's no actual functionality. Is there a better way of doing this?

**Comment by takuy** [comment]
@opdenkamp I noticed that _cec.pyd depends on Python27.dll. 

Does this mean I would need to recompile the pyd, under a modern version of python, myself to get this to work?

**Comment by opdenkamp** [comment]
This has been changed on master now. x86 is built against Python 2.7 (because of the EventGhost plugin) and x64 uses Python 3.6.
