### ISSUE TITLE
Physical Address allocation in CecSharp : Recording Device 1(Pulse eight) and Audio System( Sound bar) allocated same Physical Address.

### ISSUE THREAD

**Issue by vishwanath-tns** [Pulse-Eight/libcec#451]
Hi,
      I am using Pulse-eight Cec Adapter on windows platform. Cecsharp.dll is used to scan the devices. When scan is executed, both Recording Device 1, and Audio System are allocated same physical address. 
Please help! Following is the output

![image](https://user-images.githubusercontent.com/25783096/52320790-40109400-29f7-11e9-96cc-5182b7cbd40d.png)

Regards
Vishwanath

**Comment by vishwanath-tns** [comment]
Cec Library Version as mentioned in below screenshot

![image](https://user-images.githubusercontent.com/25783096/52320856-aeeded00-29f7-11e9-9f90-154e96495112.png)

**Comment by opdenkamp** [comment]
you have to set the `BaseDevice` and `HDMIPort` properties to the correct value when the address can't be detected by reading the EDID: https://github.com/Pulse-Eight/libcec/blob/master/src/dotnetlib/CecSharpTypes.h#L1773

try upgrading to the latest version first. if it still isn't detected correctly, set the properties mentioned above
