### ISSUE TITLE
getting error # pkg-config --cflags  -- libcec pkg-config: exec: "pkg-config": executable file not found in %PATH%

### ISSUE THREAD

**Issue by pa1shetty** [Pulse-Eight/libcec#457]
getting this error while trying to run a go file
# pkg-config --cflags  -- libcec
pkg-config: exec: "pkg-config": executable file not found in %PATH%.

**Comment by opdenkamp** [comment]
pkgconfig isn't installed on your system. see https://github.com/Pulse-Eight/libcec/blob/master/docs/README.linux.md for instructions for debian/ubuntu
