### ISSUE TITLE
EventGhost plugin not installed by 4.0.3 on windows?

### ISSUE THREAD

**Issue by kbrowder** [Pulse-Eight/libcec#464]
So I went to install libcec on windows and it looks like there's no eventghost files in the installer, so upgrading from 4.0.2 doesn't actually update eventghost.
I then opened the installers in 7-zip and it's missing the eventghost files (in the 4.0.2 installer it's in the $_16_ directory)

Any thoughts?

**Comment by kdschlosser** [comment]
Sorry for the late reply on this.

The eventghost plugin portion is still a work in progress. You can get the most recent version of the plugin as well as  how to install it from here

http://www.eventghost.net/forum/viewtopic.php?p=49838#p49838

**Comment by opdenkamp** [comment]
The plugin will be installed by default in the next version of libcec, if eventghost is found

**Comment by kdschlosser** [comment]
@opdenkamp 

I have a newer version of the plugin I can shoot it on over to ya so you can package it up.
We also need to add in some kind of a notice about needing version 0.5 of EventGhost or newer. maybe add a button in the installer so it will install EventGhost for a user that may not have it installed. Up to you. You know the installer script stuff better then I do.

Let me know.

**Comment by opdenkamp** [comment]
@kdschlosser if the version is written to the registry or to some sort of file, then it can be auto-detected by the installer

**Comment by kdschlosser** [comment]
hmmmm I am going to have to check the installer to see what it adds to the registry. I cannot remember to be honest with ya.

**Comment by kdschlosser** [comment]
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\EventGhost_is1

values MajorVersion and MinorVersion.
if MajorVersion ==  0 and MinorVersion < 5 skip installing the plugin or offer a button to upgrade the EventGhost version.
