### ISSUE TITLE
LG Magic remote doesnt work

### ISSUE THREAD

**Issue by charta77** [Pulse-Eight/libcec#482]
Hi,
I have LG TV (series 9000) connected to RPi2 with Kodi(Libreelec). HDMI cable is Audioquest Pearl.
I want use LG Magic remote to control Kodi, but It doesnt work, any button. But in generated [log](https://paste.kodi.tv/noheronizu.kodi) file I see some communication via CEC.
f.e.:
`2019-11-27 13:27:22.180 T:1600844672 WARNING: CecLogMessage - FIXME: LG seems to have bugged out. resetting to 'in transition standby to on'. the return button will not work`
Could someone help me please?

thank a lot
Petr

**Comment by kdschlosser** [comment]
CEC is a half way done protocol. There really is no requirements or certification of a device that uses CEC. So what happens is only a small part of the protocol gets used. or they use a portion of the protocol and then "add" their own pieces to it. the remote control portion seems to be one of the most common things that is left out or changed.

**Comment by charta77** [comment]
thank you for your reply. No, I didnt try cecClient. is there any cookbook how to use it with Kodi on Libreelec? thank you!
Petr

**Comment by kdschlosser** [comment]
well we need to know if the remote actually works over CEC or not. bcause if it does not work then doing anything with Kodi is going to be a waste of time.
Is your CEC adapter built onto a device (like a Raspberry Pi) or is it a USB version?

**Comment by charta77** [comment]
as I wrote I want to control Kodi(RPi2/Libreelec) with my TV's remote cotrol (LG 9000 series Magic control). Now I use to control Kodi remote MeLE F10.
But my dream is I have only one remote for TV and Kodi -> LG Magic control

**Comment by kdschlosser** [comment]
OK so I still need to have this question answered. Not all Raspberry Pi's come with CEC built into it. 
So is the CEC built into the Raspberry Pi or do you have a separate dongle plugged into the USB that handles the CEC?

**Comment by charta77** [comment]
CEC is built into the RPi2.
thank you for your time

**Comment by kdschlosser** [comment]
no worries m8. ok so no option to run windows.

I can hammer out a python script you can run which will provide really detailed logs. give me a day or so to get that together for ya so we can see exactly what is happening.

**Comment by charta77** [comment]
you are great! thank you very much

**Comment by charta77** [comment]
I would like to ask you about the script - is there any good news?
thanks
Petr

**Comment by charta77** [comment]
@kdschlosser Hi,
is there any chance to do the script?
thank you

**Comment by charta77** [comment]
@kdschlosser Hi Kevin, is something new about the script? thanks

**Comment by opdenkamp** [comment]
Sorry for the delay. LG's magic remote does not use CEC. It can only control the TV.
As for that warning: that one can show up if the HDMI port isn't set up correctly in Kodi. You can configure it in Kodi, or move to HDMI 1 of the TV (default setting)

**Comment by charta77** [comment]
@opdenkamp thank you for your reply.
If the magic remote doesnot uses CEC, why my TV (9000 series) support Simplink(hdmi-cec)? So I think some cec communication between TV and Kodi may exists... thank you and have a nice day
Petr

**Comment by opdenkamp** [comment]
Because your TV also supports the standard IR remote, and you can use features like selecting an HDMI input.

**Comment by charta77** [comment]
ok,thank you

**Comment by charta77** [comment]
@opdenkamp  It works :)

**Comment by jekkos** [comment]
@charta77 How did you get it to work in the end?

**Comment by charta77** [comment]
@jekkos Hi,
simply via device connector. The Kodi is defaultly set as blu ray so set it as "other box".

**Comment by jekkos** [comment]
It seems my CEC link is working in some way (it IS turning on my LG beamer) , also tried to echo ON and pipe it to cec-client, which also works... However no buttons whatsoever.

Do you have it directly connected to your HDMI on raspberry pi or do you use an extra device in between? Do you use a special remote.xml? If yes would you mind to share?

**Comment by charta77** [comment]
RasPi is connected directly (hdmi 2.0 cable), without special remote.xml

**Comment by FireEmerald** [comment]
> Sorry for the delay. LG's magic remote does not use CEC. It can only control the TV.
> As for that warning: that one can show up if the HDMI port isn't set up correctly in Kodi. You can configure it in Kodi, or move to HDMI 1 of the TV (default setting)

It is possible to control Kodi with your Magic Remote on a LG smart TV.
My issue was a wrong configuration inside the "Home Dashboard" of the LG smart TV.

**How to reset the configured device in your LG smart TV:**
> Ok, first, when I connected the HDMI cable to the TV, the raspberry was identified like a Roku and categorized in the Set-Top Box/OTT group. The remote control was not able to interact with raspberry. Simplink (HDMI-CEC) was ON in the connection settings options.

> Some time later, after several attempts, and after a new try removing and reconnecting the raspberry HDMI cable in another port, I realized in just one of the categories listed in the Device Connector page, where you can find: Set-Top Box/OTT, Game Console, Home Theater etc, exactly in the Set-Top Box/OTT, an interesting button, the reset device button. So, I just clicked on it and got out that page and returned to Raspberry input to check if I had success, and for my happiness, yes, remote control working.

I found the solution here: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=231676#p1637861

**Comment by mlindner** [comment]
> Sorry for the delay. LG's magic remote does not use CEC. It can only control the TV.

This is not true. It can control other devices perfectly fine. If you mean the "magic mouse" part of the controller no, that can't be used, but button presses go across CEC from the TV without issue.

**Comment by malard** [comment]
Sounds like they improved it since I last looked then!

**Comment by jekkos** [comment]
I'm quite convinced that it does have some CEC capabilities, however I was unable to make it work and gave up. Eventually I went with good old gpio receiver on the rpi that now uses my amplifier's remote (2 in one), which is even nicer in fact.
