### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by kdschlosser** [Pulse-Eight/libcec#483]
I think the last time @opdenkamp was active was on December 3 of 2018 or there abouts.. are any fixes/upgrades going to be made to this repository anymore?

**Comment by malard** [comment]
Yes they will, we will be in touch next week

Thanks

From my phone


-------- Original Message --------
Subject: [Pulse-Eight/libcec] Is this project dead? (#483)

**Comment by kdschlosser** [comment]
@malard thanks for the reply. I hope business is going well over there at PulseEight. I would love to be able to get some more of the protocol added to libcec.

**Comment by opdenkamp** [comment]
I've merged in the first batch of pull requests and some more changes are on it's way. Thanks
