### ISSUE TITLE
USB-CEC adapter/driver does not work with Samsung RU7100 TV

### ISSUE THREAD

**Issue by stojy** [Pulse-Eight/libcec#491]
As per the attached [adapter logs](https://github.com/Pulse-Eight/libcec/files/4142296/adapter.logs.txt), the Pulse Eight does not appear to work with the Samsung RU7100.

I've tried the following without any success..
- Installed latest libcec 4.0.3 driver (win10)
- Upgraded adapter firmware to latest v9
- Cold (re)booted PC and TV numerous times in various permutations
- Tried 4 different high quality HDMI cables.  Including a brandnew HDMI 2.0b certified cable that explicitly stated CEC compatibility.  Also used a multi-meter to confirm pin 13 is connected within the cable.
- Confirmed Samsung TV has latest fimrware (v1335.0)
- Confirmed Samsung TV Anynet is enbabled
- Trawled the github issues and various internet posts for a solution

**Is there anything I can do to fix/workaround this issue?**  I hope this is the case as I've only just received the adaptor yesterday!

**Comment by opdenkamp** [comment]
The CEC line is constantly pulled low. Try disconnecting any other HDMI equipment.

If you don't have any other HDMI devices, then it's faulty adapter, faulty video card or faulty TV. If you have another CEC compatible screen, try that one. If it works, then the TV is faulty.

If that one doesn't work either, then you'll need a cec-less HDMI cable or a new adapter. Please contact support@pulse-eight.com if you need assistance.
