### ISSUE TITLE
new Hisense TV almost working but....

### ISSUE THREAD

**Issue by Condorello** [Pulse-Eight/libcec#493]
Hi, i've a Rpi connected to a new Hisense TV. Cec control of the rasperry using the tv remote is slow, with a delay on key pression, but works. What is not working is the power off which is sent from Rpi to the TV. Seems that the tv vendor is not recognized or similar, but the previus tv was a 3 years old Hisense, recognized as Vizio. Probably the producer changed it's manufater id. How can i try to start fixing that? Maybe from start recognized the vendor? All key pression from tv remote to Rpi is working, the problems is in the reverse transmition, from Rpi to TV:
Thanks

    CEsala:~ # echo 'standby 0' | cec-client -s
    opening a connection to the CEC adapter...
    DEBUG:   [             114]	Broadcast (F): osd name set to 'Broadcast'
    NOTICE:  [             114]	connection opened
    DEBUG:   [             114]	<< Broadcast (F) -> TV (0): POLL
    TRAFFIC: [             114]	<< f0
    DEBUG:   [             114]	processor thread started
    DEBUG:   [             171]	>> POLL sent
    DEBUG:   [             171]	TV (0): device status changed into 'present'
    DEBUG:   [             171]	<< requesting vendor ID of 'TV' (0)
    TRAFFIC: [             171]	<< f0:8c
    DEBUG:   [            1252]	expected response not received (87: device vendor id)
    TRAFFIC: [            1252]	<< f0:8c
    TRAFFIC: [            1554]	>> 0f:00:8c:00
    DEBUG:   [            1554]	marking opcode 'give device vendor id' as unsupported feature for device 'TV'
    DEBUG:   [            1554]	>> TV (0) -> Broadcast (F): feature abort ( 0)
    DEBUG:   [            1555]	expected response received (87: device vendor id)
    NOTICE:  [            1555]	registering new CEC client - v4.0.4
    DEBUG:   [            1555]	detecting logical address for type 'recording device'
    DEBUG:   [            1555]	trying logical address 'Recorder 1'
    DEBUG:   [            1555]	<< Recorder 1 (1) -> Recorder 1 (1): POLL
    TRAFFIC: [            1555]	<< 11
    WARNING: [            1919]	Write: write failed
    TRAFFIC: [            1920]	<< 11
    WARNING: [            1920]	Write: write failed
    DEBUG:   [            1920]	>> POLL not sent
    DEBUG:   [            1920]	using logical address 'Recorder 1'
    DEBUG:   [            1920]	Recorder 1 (1): device status changed into 'handled by libCEC'
    DEBUG:   [            1920]	Recorder 1 (1): power status changed from 'unknown' to 'on'
    DEBUG:   [            1920]	Recorder 1 (1): vendor = Pulse Eight (001582)
    DEBUG:   [            1920]	Recorder 1 (1): CEC version 1.4
    DEBUG:   [            1920]	AllocateLogicalAddresses - device '0', type 'recording device', LA '1'
    DEBUG:   [            1923]	Recorder 1 (1): osd name set to 'CECTester'
    DEBUG:   [            1923]	Recorder 1 (1): menu language set to 'eng'
    DEBUG:   [            1923]	AutodetectPhysicalAddress - autodetected physical address '2000'
    DEBUG:   [            1923]	Recorder 1 (1): physical address changed from ffff to 2000
    DEBUG:   [            1923]	<< Recorder 1 (1) -> broadcast (F): physical address 2000
    TRAFFIC: [            1923]	<< 1f:84:20:00:01
    NOTICE:  [            2077]	CEC client registered: libCEC version = 4.0.4, client version = 4.0.4, firmware version = 5, logical address(es) = Recorder 1 (1) , physical address: 2.0.0.0,  compiled on Wed Nov 27 08:01:29 UTC 2019 by adamg@zulu on Linux 4.15.0-71-generic (x86_64), features: P8_USB, DRM, P8_detect, AOCEC
    DEBUG:   [            2077]	<< Recorder 1 (1) -> TV (0): OSD name 'CECTester'
    TRAFFIC: [            2077]	<< 10:47:43:45:43:54:65:73:74:65:72
    DEBUG:   [            2379]	<< requesting power status of 'TV' (0)
    TRAFFIC: [            2379]	<< 10:8f
    TRAFFIC: [            2758]	>> 01:90:00
    DEBUG:   [            2758]	TV (0): power status changed from 'unknown' to 'on'
    DEBUG:   [            2758]	>> TV (0) -> Recorder 1 (1): report power status (90)
    DEBUG:   [            2758]	expected response received (90: report power status)
    DEBUG:   [            2758]	<< requesting vendor ID of 'TV' (0)
    DEBUG:   [            2758]	'give device vendor id' is marked as unsupported feature for device 'TV'
    NOTICE:  [            2758]	<< putting 'TV' (0) in standby mode
    TRAFFIC: [            2758]	<< 10:36
    DEBUG:   [            2839]	unregistering all CEC clients
    NOTICE:  [            2840]	unregistering client: libCEC version = 4.0.4, client version = 4.0.4, firmware version = 5, logical address(es) = Recorder 1 (1) , physical address: 2.0.0.0,  compiled on Wed Nov 27 08:01:29 UTC 2019 by adamg@zulu on Linux 4.15.0-71-generic (x86_64), features: P8_USB, DRM, P8_detect, AOCEC
    DEBUG:   [            2840]	Recorder 1 (1): power status changed from 'on' to 'unknown'
    DEBUG:   [            2840]	Recorder 1 (1): vendor = Unknown (000000)
    DEBUG:   [            2840]	Recorder 1 (1): CEC version unknown
    DEBUG:   [            2840]	Recorder 1 (1): osd name set to 'Recorder 1'
    DEBUG:   [            2840]	Recorder 1 (1): device status changed into 'unknown'
    DEBUG:   [            2842]	unregistering all CEC clients

and here the cec scan:

    CEsala:~ # echo "scan" | cec-client -s -d 1
    opening a connection to the CEC adapter...
    requesting CEC bus information ...
    ERROR:   [           17626]	failed to request the physical address
    CEC bus information
    ===================
    device #0: TV
    address:       0.0.0.0
    active source: no
    vendor:        Unknown
    osd string:    TV
    CEC version:   1.4
    power status:  on
    language:      ita

    device #1: Recorder 1
    address:       2.0.0.0
    active source: no
    vendor:        Pulse Eight
    osd string:    CECTester
    CEC version:   1.4
    power status:  on
    language:      eng

    device #5: Audio
    address:       f.f.f.f
    active source: no
    vendor:        Yamaha
    osd string:    ATS-2070
    CEC version:   1.4
    power status:  unknown
    language:      ???

    currently active source: unknown (-1)

**Comment by opdenkamp** [comment]
If the power off command doesn't work, while all of the rest (other than the reported vendor id) does work, then it's usually caused by a setting on the TV, called "auto standby" or similar. Some TVs don't support the power off command at all, like most LG screens. This isn't a libCEC issue.
