### ISSUE TITLE
A lot of products do not work: TV, Home cinema, ...

### ISSUE THREAD

**Issue by Neustradamus** [Pulse-Eight/libcec#498]
A lot of products do not work: TV, Home cinema, ...

Here:
- https://dev.freebox.fr/bugs/index/proj0?string=cec&project=0&search_name=&type[0]=&sev[0]=&pri[0]=&due[0]=&reported[0]=&cat[0]=&status[0]=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=&do=index&order=id&sort=desc

For solved products, I do not know solution used, but can you look for add directly?

**Comment by opdenkamp** [comment]
sorry, but I don't know this product but if it uses libCEC and something doesn't work, then a ticket will have to be created here. I can't look into another project's (french) bugtracker to search for potential libCEC issues.
