### ISSUE TITLE
libCecTray improvements 

### ISSUE THREAD

**Issue by peches** [Pulse-Eight/libcec#5]
One simple request. In XBMC tab there is an option for suspend PC when the TV is off. This option should works with MCE too.
And new option "Wake PC when TV is on" would be handy. 
This functions is working perfect in 3rd party tool CECTray from chir21.

**Comment by opdenkamp** [comment]
libCECTray will send the PC to standby in the next version, similar to the code that you linked, and the "poll failed" error when resuming from standby will be gone

**Comment by mattiasost** [comment]
I thought this task was about supporting "pc standby" without having to run xbmc. How about such an option?
