### ISSUE TITLE
Kodi does not shutdown

### ISSUE THREAD

**Issue by Enominus** [Pulse-Eight/libcec#502]
Hi all,

thx for this great feature. I have a pulse eight hdmi cec adapter, a win 10 HTPC with the latest Kodi and a LG Beamer. In general, everything works fine - I am able to control kodi with my LG remote. But I have one problem: When I configure in kodi settings "When TV ist switched of: shutdown", Kodi does not shutdown. Kodi instead quits itselfs, the win 10 desktop appears. What works: When I configure "standby", Kodi goes correctly in standby mode. But I dont like the standby function. More over I would like to use the shutdown function. Is this a known bug? Is there a known workaround? 

thx in advance!
Enominus

**Comment by Sudrien** [comment]
https://wiki.gentoo.org/wiki/Kodi currently has a udev/polkit rule at the bottom of the page to allow this

**Comment by Enominus** [comment]
Hi Sudrien,

thanks for your reply! Unfortunately I'm a rookie with very less experience. Could you please give me a step by step instruction how I could solve my problem?

thx!

**Comment by Sudrien** [comment]
Not having a windows machine available, I can direct you to https://forum.kodi.tv/showthread.php?tid=217477 - it seems to match your description.

**Comment by Enominus** [comment]
yea that helped! Thanks for your support!
