### ISSUE TITLE
standby monitor defaults to hdmi 1 on sony x800 43 tv, cant tell it to wake up on hdmi 3 etc?

### ISSUE THREAD

**Issue by markm75** [Pulse-Eight/libcec#508]
Is there any way to specify a different hdmi port for the monitor, running 4.03 now.

**Comment by opdenkamp** [comment]
the standby monitor tool has been integrated into cec-tray now and this issue has been fixed: https://github.com/Pulse-Eight/libcec/releases/download/libcec-6.0.0/libcec-6.0.0.exe
