### ISSUE TITLE
Option "Pause playback when switching to another source" unpauses player if it's already paused

### ISSUE THREAD

**Issue by tomekceszke** [Pulse-Eight/libcec#51]
I just noticed that behavior on default Raspbmc distro (Raspberry Pi B+, Kodi stable, libCEC 2.2.-firmware v1).

To reproduce:
1. Check option: Pause playback when switching to another source in libCEC plugin settings 
2. Play a movie
3. Pause it
4. Change TV input source
5. Kodi will unpause the player 

I would suggest to check current player status before send command pause.

**Comment by opdenkamp** [comment]
see https://github.com/xbmc/xbmc/pull/6236
