### ISSUE TITLE
cectypes.h missing an enum entry for CEC version 0x06 as used by Apple TV

### ISSUE THREAD

**Issue by jsiegenthaler** [Pulse-Eight/libcec#518]
cectypes.h is missing an enum entry for CEC v2.0

My Apple TV 4K model A1842 made in 2018 reports a CEC version of 0x06 (message: 41:9e:06)

cectypes.h contains:
```

typedef enum cec_version
{
  CEC_VERSION_UNKNOWN = 0x00,
  CEC_VERSION_1_2     = 0x01,
  CEC_VERSION_1_2A    = 0x02,
  CEC_VERSION_1_3     = 0x03,
  CEC_VERSION_1_3A    = 0x04,
  CEC_VERSION_1_4     = 0x05
} cec_version;

```
Value 0x06, as issued by Apple TVs, most likely it is CEC version 2.0

https://patchwork.kernel.org/patch/6328571/ 
concurs that 0x06 is CEC_VERSION_2_0

Can you update cectypes.h  please ?

**Comment by opdenkamp** [comment]
I've added it in d5cb47593e8f23937d1772c1d4a8f5b106bc2e87
