### ISSUE TITLE
question: filter commands with pulses adapter

### ISSUE THREAD

**Issue by hansbogert** [Pulse-Eight/libcec#536]
Can the pulse eight cec adapter filter out specific commands coming from the device attached to the IN port?

Im hoping to stop a chromecast from broadcasting power on commands  to my tv screen, but keep the rest of the cec spec for lip sync etc.

It's idiotic that devices incl.chromecasts give so little.configurstion options.

**Comment by malard** [comment]
No

It doesn't do any NAT or firewall style filtering

However our video matrixes do !


Sent from my Huawei phone


-------- Original message --------

**Comment by hansbogert** [comment]
That's too bad, thanks for answer though!
