### ISSUE TITLE
Where to get CEC-TRAY application for Windows?

### ISSUE THREAD

**Issue by filimonic** [Pulse-Eight/libcec#563]
Where to get CEC-TRAY application for Windows?

**Comment by badbob001** [comment]
I see it in my installation:

- C:\Program Files (x86)\Pulse-Eight\USB-CEC Adapter\x64\netfx\cec-tray.exe
- C:\Program Files (x86)\Pulse-Eight\USB-CEC Adapter\x86\netfx\cec-tray.exe
