### ISSUE TITLE
cec-tray hangs on windows

### ISSUE THREAD

**Issue by gorrus** [Pulse-Eight/libcec#88]
After some time, cec-tray process starts to consume too much cpu. When I open tray app and go to log output - it hangs completely, so I expect this is connected to logging somehow.
I tried restarting it and unchecking all checkboxes in log output (errors, traffic, etc.), after that it does not hang. Unfortunately, after restart this is not preserved and it logs everything again. 
v2.2.0 (x64)

**Comment by opdenkamp** [comment]
should be fixed in the next version of libCEC, which will be on our website soon. you can download the beta build here: https://dl.dropboxusercontent.com/u/59212404/libcec-3.0.0.exe

**Comment by gorrus** [comment]
Great, thanks!
I've installed it, there were some errors during the installation
![image](https://cloud.githubusercontent.com/assets/10279003/7449485/1f6a9568-f240-11e4-966e-51486b08546d.png)
will report how it works

**Comment by opdenkamp** [comment]
ok thanks, that must be the check for the new plugin that doesn't work correctly, I'll get that fixed.

**Comment by gorrus** [comment]
it is all the same in 3.0.0,
here is a stack trace from process explorer
![image](https://cloud.githubusercontent.com/assets/10279003/7467512/f2fe7c24-f302-11e4-98f4-90b822b45501.png)

**Comment by gorrus** [comment]
I have to restart tray app every day :(
Is there any way I could help with the issue?

**Comment by opdenkamp** [comment]
I'll have to reproduce this in the debugger, that stack points to something external crashing for some reason. may be the log tab filling up.

**Comment by opdenkamp** [comment]
log tab didn't have an upper limit. fixed in master (will be committed in a bit)

**Comment by gorrus** [comment]
Super, thanks! Can I have a nightly build bits or something?

**Comment by gorrus** [comment]
It seems that I can download only 3.0.0 windows binary that does not contain the fix. Where can I get 3.1.0 for windows?

**Comment by opdenkamp** [comment]
The latest version of the software can be found on https://www.pulse-eight.com/p/104/usb-hdmi-cec-adapter
