### ISSUE TITLE
LG Simplink not working with libcec

### ISSUE THREAD

**Issue by dcolens** [Pulse-Eight/libcec#92]
Exact same issue as #37 

It is not possible to use the Simplink menu or changing source to get the remote connected to xbmc with the latest openelec. 

reverted back to 2.1.0 which kind of works. I'll add a pastebin, when I try again, but given the behaviour is 100% the same as with pre-3.0.0 releases, not sure it will include more details.

**Comment by opdenkamp** [comment]
re-opened the previous ticket. please attach the log there
