### ISSUE TITLE
cec-client blocks kodi and vice versa for about 500s

### ISSUE THREAD

**Issue by mkreisl** [Pulse-Eight/libcec#94]
Using RPi 1B with Kodi 15.0b2 on XBian and cec-client running in background for auto-powering-off the TV

The program which is started first gets no CEC events for 500s after starting the second program. After this timeout, all events occured before are processed normally. In other words, no event will be lost but only with a delay of 500s.

This issue comes with libcec v2.2.0 and still remains in libcec v3.0.0

This is a bad situation because mostly after power-up of the TV you have to wait 500s until you can control Kodi.

**Comment by opdenkamp** [comment]
cec-client and libCEC (kodi's integration) are supposed to block each other. when using a USB-CEC adapter, we don't even allow it, and it looks like I should move this 1 layer up so you don't try this on the pi either ;-) as for the 500s delay, that's a bit too much indeed and #96 seems to fix this.
