### ISSUE TITLE
Kodi: Option to pause or stop playback when tv is off 

### ISSUE THREAD

**Issue by fluxtendu** [Pulse-Eight/libcec#98]
Hi,

Libcec options in kodi: "shutdown and suspend when tv is off" are not usable when the device is a raspberry pi or when it have other purposes than playback, therefore I will be glad to have an option to pause (or stop) Kodi playback when tv is off.

Thanks

**Comment by c-o-m-m-a-n-d-e-r** [comment]
+1

**Comment by filimonic** [comment]
+1

**Comment by opdenkamp** [comment]
this is not something for libCEC, but for Kodi's integration with it.
